- docs/source/user_guide/cli/opctl/configure.rst
"Science" was misspelled in configure.rst
> Fixed misspelling

- README.md
moving from docs.oracle.com to readthedocs for ADS documentation.
> directing ADS docs links to readthedocs

- docs/source/release_notes.rst
Fixes typos in release notes for 2.6.9 and 2.7.0 versions.
> Fixes release notes.

- docs/source/user_guide/apachespark/dataflow-spark-magic.rst
- docs/source/user_guide/model_registration/quick_start.rst
This PR aims to fix the example in ads docs.
* `%use_session` in dataflow-spark-magic
* `Quick start` example of using PyTorch Framework.
> fix example in ads docs

- docs/source/user_guide/model_version_set/index.rst
https://jira.oci.oraclecorp.com/browse/ODSC-36680
[MVS][User Guide] Add Model Version Set user guide.
* Adds limited availability flag to the MVS documentation.
> ODSC-36680: Adds LA flag for the MVS user guide.

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- added bug report template
- added config.yml
> ODSC-37075. Create a bug template for github issues

- docs/source/user_guide/model_catalog/model_catalog.rst
- docs/source/user_guide/model_registration/frameworks/automlmodel.rst
- docs/source/user_guide/model_registration/frameworks/lightgbmmodel.rst
- docs/source/user_guide/model_registration/frameworks/pytorchmodel.rst
- docs/source/user_guide/model_registration/frameworks/sklearnmodel.rst
- docs/source/user_guide/model_registration/frameworks/sparkpipelinemodel.rst
- docs/source/user_guide/model_registration/frameworks/tensorflowmodel.rst
- docs/source/user_guide/model_registration/frameworks/xgboostmodel.rst
- docs/source/user_guide/model_registration/model_artifact.rst
- docs/source/user_guide/model_registration/model_deploy.rst
- docs/source/user_guide/model_registration/model_file_customization.rst
- docs/source/user_guide/model_registration/model_metadata.rst
- docs/source/user_guide/model_serialization/automlmodel.rst
- docs/source/user_guide/model_serialization/pytorchmodel.rst
- docs/source/user_guide/model_serialization/quick_start.rst
- docs/source/user_guide/model_serialization/sklearnmodel.rst
- docs/source/user_guide/model_serialization/tensorflowmodel.rst
- docs/source/user_guide/model_serialization/xgboostmodel.rst
The [code examples](https://accelerated-data-science.readthedocs.io/en/latest/user_guide/model_registration/frameworks/xgboostmodel.html#example) copied from quick start guide gives warning message -
```
WARNING:py.warnings:/tmp/ipykernel_2025/2352313256.py:2: DeprecationWarning: The `ads.common.model_metadata` is deprecated in `oracle-ads 2.6.8` and will be removed in future release. Use the `ads.model.model_metadata` instead.
from ads.common.model_metadata import UseCaseType
```
We need to update all the examples to remove the deprecated code.
> ODSC-36926/replaced ads.common.model_metadata with ads.model.model_metadata

- docs/source/user_guide/model_catalog/model_catalog.rst
- docs/source/user_guide/model_registration/frameworks/automlmodel.rst
- docs/source/user_guide/model_registration/frameworks/lightgbmmodel.rst
- docs/source/user_guide/model_registration/frameworks/pytorchmodel.rst
- docs/source/user_guide/model_registration/frameworks/sklearnmodel.rst
- docs/source/user_guide/model_registration/frameworks/sparkpipelinemodel.rst
- docs/source/user_guide/model_registration/frameworks/tensorflowmodel.rst
- docs/source/user_guide/model_registration/frameworks/xgboostmodel.rst
- docs/source/user_guide/model_registration/model_artifact.rst
- docs/source/user_guide/model_registration/model_deploy.rst
- docs/source/user_guide/model_registration/model_file_customization.rst
- docs/source/user_guide/model_registration/model_metadata.rst
- docs/source/user_guide/model_serialization/automlmodel.rst
- docs/source/user_guide/model_serialization/pytorchmodel.rst
- docs/source/user_guide/model_serialization/quick_start.rst
- docs/source/user_guide/model_serialization/sklearnmodel.rst
- docs/source/user_guide/model_serialization/tensorflowmodel.rst
- docs/source/user_guide/model_serialization/xgboostmodel.rst
Reverts oracle/accelerated-data-science#55
The original PR was merged to `main`. Need to be reverted and create a new PR to merge the change into`2.7.x`.
> Revert "ODSC-36926/replaced ads.common.model_metadata with ads.model.model_metadata"

- docs/source/release_notes.rst
- docs/source/user_guide/model_version_set/index.rst
add a release notes for ads 2.7.3 and remove the beta mark for model version set feature
> TC 23367/release notes 2.7.3

- docs/source/ads.jobs.rst
- docs/source/conf.py
The ADS path in sphinx config `conf.py` is incorrect. This path is needed for Sphinx to build the latest ADS class documentation. Class documentation might be missing or outdated because of this.
For example, the class documentation for the newly added huggingface model is missing: https://accelerated-data-science.readthedocs.io/en/latest/ads.model.framework.html#ads-model-framework-huggingface-model-module
This PR also updates the TOC tree level in the class documentation for Jobs.
> Update sphinx config

- docs/source/user_guide/model_registration/model_artifact.rst
The policy showing in the [user guide](https://accelerated-data-science.readthedocs.io/en/latest/user_guide/model_registration/model_load.html#large-model-artifacts) is incorrect. Based on the [OCI documentation](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/copyingobjects.htm#ariaid-title4), region identifier is required for object storage service when writing the policy, otherwise user will get an error (name of the service is wrong).
> Update user guide for large model artifact to add region identifier to policy example.

- ads/model/generic_model.py
- tests/unitary/with_extras/model/test_generic_model.py
Related JIRA:https://jira.oci.oraclecorp.com/browse/ODSC-39737
Currently, the GenericModel supports two methods that can be used to test the model:
* verify()
* predict()
The difference between these two methods is that verify is used for local testing, where predict sends the request to the ML endpoint. Having two different methods confuses users, they don't really understand why we need two different methods for inferring the model. 
* Add a new attribute - `local=True/False` to the predict method to be able to invoke the prediction locally.
```
prediction = GenericModel.predict(local=True)
```
TC: https://teamcity.oci.oraclecorp.com/buildConfiguration/Odsc_Ads_AdsCiCd_CiTrigger/38127161?buildTab=buildParameters
> ODSC-39737 : allow to use `GenericModel.predict()` locally

- .github/workflows/publish-to-pypi.yml
- setup.py
We need action which will publish ADS to PyPI. 
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-37152
1. I've created account in TestPyPI
2. Created publish-to-pypi.yml with step to publish to TestPyPI
3. Manually triggered Action - [DO NOT TRIGGER] Publish to PyPI
4. Observed logs showing success and artifact uploaded - check the logs: https://github.com/oracle/accelerated-data-science/actions/runs/4622770194/jobs/8175860530
5. Checked TestPyPI has test ads project published: https://test.pypi.org/project/test-oracle-ads/2.8.3/
6. Updated publish-to-pypi.yml - commented out publish to TestPyPI, added publish to real PyPI
> Add action for publish ADS to PyPI

- tests/unitary/with_extras/model/test_model_framework_tensorflow_model.py
Using a local file as lock to make sure the load_data() of MNIST dataset finishes before any other process access it.
When collecting the tests with multiple workers, each worker will try to collect all the tests in parallel (even though a worker will only run some of the tests). Each worker will run the code in the `setup_class` during the test collection. This might cause errors when running `mnist.load_data()` because it will cache the data at a fixed location (`~/.keras/datasets/mnist.npz`) and the data will be reused if exist. However, when multiple processes are running `mnist.load_data()`, for example, the first process will create the cache file and start the downloading, and the second process may see the file already exists so it will try to load the file while it is still being …
> Fix TF model tests errors when running in parallel.

- docs/source/user_guide/configuration/authentication.rst
This PR has to be merged to main (first) to validate auto-trigger of readthedocs build, which should build latest readthedocs. Same change will be added to develop with another PR.
> Add information about AuthContext context class with link to api doc

- ads/ads
ADS supports `python3` only. When user is using `python2` as default in their system, it might cause trouble for them to run ADS CLI if we don't explicitly call `python3`.
> Update ads CLI to explicitly use python3

- .github/workflows/run-unittests-default_setup.yml
- .github/workflows/run-unittests.yml
- tests/unitary/default_setup/auth/test_auth.py
- tests/unitary/default_setup/catalog/test_catalog_notebook.py
- tests/unitary/default_setup/catalog/test_catalog_project.py
- tests/unitary/with_extras/vault/test_vault_vault.py
A couple tests requires environment variables to be set before running them, otherwise there will be an error collecting the tests. I think it is better for the tests to have less dependency on the environment. This PR adds a default value value if the environment variable is not set.
> Update unit tests to set compartment ID if it is not available from environment variables.

- ads/dataset/classification_dataset.py
- ads/dataset/dataset.py
- ads/dataset/dataset_with_target.py
- ads/dataset/forecasting_dataset.py
- ads/dataset/helper.py
- ads/dataset/regression_dataset.py
- docs/source/user_guide/data_transformation/data_transformation.rst
- docs/source/user_guide/loading_data/connect.rst
- docs/source/user_guide/loading_data/connect_legacy.rst
- docs/source/user_guide/loading_data/supported_format.rst
- docs/source/user_guide/model_catalog/model_catalog.rst
- docs/source/user_guide/quickstart/quickstart.rst
- tests/unitary/with_extras/dataset/data/orcl_attrition.csv
- tests/unitary/with_extras/dataset/test_dataset_dataset.py
- tests/unitary/with_extras/dataset/test_dataset_target.py
- Initialize ads dataset instance from `ADSDataset` constructor
- Initialize ads dataset with target from `ADSDatasetWithTarget` constructor
- Build ads dataset instance from `from_dataframe()` of `ADSDataset`
- Build ads dataset with target from `from_dataframe()` of `ADSDatasetWithTarget`
Example
```
employees = ADSDatasetWithTarget.from_dataframe(
df=pd.read_csv("oci://hosted-ds-datasets@bigdatadatasciencelarge/synthetic/orcl_attrition.csv"),
target="Attrition",
storage_options={'config':{},'region':'us-ashburn-1'}
).set_positive_class('Yes')
employees = ADSDatasetWithTarget(
df=pd.read_csv("oci://hosted-ds-datasets@bigdatadatasciencelarge/synthetic/orcl_attrition.csv"),
target="Attrition",
storage_options={'config':{},'region':'us-ashburn-1'}
)
employees = ADSDataset( …
```
> Modified ADS dataset class

- docs/source/release_notes.rst
- docs/source/user_guide/apachespark/quickstart.rst
- docs/source/user_guide/jobs/data_science_job.rst
- docs/source/user_guide/jobs/overview.rst
- docs/source/user_guide/jobs/yaml_schema.rst
- docs/source/yaml_schema/jobs/job.html
- docs/source/yaml_schema/jobs/job.yaml
A small PR with spelling fixes
> Spelling fixes

- .readthedocs.yaml
When readthedocs tried to build documentation it failed for the reason of having very-very old OpenSSL on board (6 years old). Investigation showed that by default readthedocs will use old ubuntu for builders (which are alos 6 years old). We need to specify newer version of ubuntu and also we need fresher version of python *by default readthedocs installing pythoin3.7).
This ^ can be fixed by special configuration yaml file - documentation: https://docs.readthedocs.io/en/stable/config-file/v2.html#. In this yaml we spoeficy new ubuntu and python 3.9
- added .readthedocs.yaml with ubuntu-22.04 and python 3.9
> Hotfix for readthedocs builder

- docs/source/user_guide/cli/authentication.rst
- docs/source/user_guide/model_registration/frameworks/huggingfacemodel.rst
- docs/source/user_guide/model_registration/frameworks/lightgbmmodel.rst
- docs/source/user_guide/model_registration/frameworks/pytorchmodel.rst
- docs/source/user_guide/model_registration/frameworks/sklearnmodel.rst
- docs/source/user_guide/model_registration/frameworks/sparkpipelinemodel.rst
- docs/source/user_guide/model_registration/frameworks/tensorflowmodel.rst
- docs/source/user_guide/model_registration/frameworks/xgboostmodel.rst
Several links to API documentation in model frameworks were broken. Apart of what was reported in bug ticket searched for other similar broken links to fix them all.
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-39272
- change model_framework to model.framework in links to API documentation for frameworks
- added recent change to cli/authentication.rst, which was wrongly added into incorrect configuration/authentication.rst (approved and merged in this PR: https://github.com/oracle/accelerated-data-science/pull/158/files)
In Github rendered rst files can't validation those links. For validation builded docs locally and checked - links working - not 404 error when click API Documentation on (for example) huggingfacemodel page:
> ODSC-39272. Fix for links of See API documentation

- ads/common/utils.py
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-42685
User reported the api doc for `ads.common.utils.copy_file` is incomplete: the progressbar_description parameter is not documented. 
Improved api doc for `ads.common.utils.copy_file`.
> Fix api doc for `ads.common.utils.copy_file`

- ads/dataset/dataset.py
- tests/unitary/with_extras/dataset/test_dataset_dataset.py
Added user-friendly error message when methods suggest_recommendations() or get_recommendations() invoked without specifying target parameter.
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-38735
- added suggest_recommendations() with message to the user that the user needs to set the target
- added get_recommendations() with message to the user that the user needs to set the target
- added unittest
> Fix API, that gives an error if target is not specified

- ads/common/auth.py
- docs/source/user_guide/cli/authentication.rst
- tests/unitary/default_setup/auth/test_auth.py
- tests/unitary/default_setup/telemetry/test_agent.py
- tests/unitary/with_extras/opctl/test_opctl_core_site.py
- Support private key content through `config`
- Added validation for config
```
private_key_content = """
-----BEGIN RSA PRIVATE KEY-----
KEY_CONTENT
-----END RSA PRIVATE KEY-----
"""
config = {
"user": "ocid1.user.oc1..xxx",
"fingerprint": "34:78:73:45:0e:sd:f2:34:df:5s:f1:1b:de:b1:3d:f6",
"tenancy": "ocid1.tenancy.oc1..xxxx",
"region": "us-ashburn-1",
"key_content":private_key_content,
}
ads.set_auth("api_key", config=config)
```
> Added support for private key content for set_auth()

- ads/jobs/ads_job.py
- ads/jobs/builders/infrastructure/dsc_job.py
```
job_run = job.run(
name="<my_job_run_name>",
args="new_arg --new_key new_val",
env_var={"new_env": "new_val"},
freeform_tags={"new_tag": "new_tag_val"},
defined_tags={"Operations": {"CostCenter": "42"}}
)
```
> Added support for overriding defined tags in ads job run.

- ads/jobs/builders/infrastructure/dataflow.py
- docs/source/user_guide/apachespark/dataflow.rst
- docs/source/user_guide/apachespark/quickstart.rst
- tests/unitary/default_setup/jobs/test_jobs_dataflow.py
- Added `with_freeform_tag()` and `with_defined_tag()` in `DataFlow` class. Note these two APIs end without `s` similar as [DataScienceJob](https://github.com/oracle/accelerated-data-science/blob/main/ads/jobs/builders/infrastructure/dsc_job.py#L1282-1300).
```
DataFlow()
.with_driver_shape("VM.Standard.E4.Flex")
.with_driver_shape_config(ocpus=2, memory_in_gbs=32)
.with_executor_shape("VM.Standard.E4.Flex")
.with_executor_shape_config(ocpus=4, memory_in_gbs=64)
.with_spark_version("3.2.1")
.with_freeform_tag(test_freeform_key="test_freeform_value")
.with_defined_tag(**{"Oracle-Tags": {"CreatedBy": "test_name@oracle.com"}})
```
> Added defined tags for data flow

- ads/jobs/builders/infrastructure/dsc_job.py
- tests/unitary/default_setup/jobs/test_jobs_base.py
Validation for:
- No shape config is needed for non-flex shape
> Added checker for shape details for job

- ads/common/dsc_file_system.py
- ads/jobs/builders/infrastructure/dsc_job.py
- tests/unitary/default_setup/jobs/test_jobs_mount_file_system.py
- Implemented new class `OCIObjectStorage` for mounting OSS
```
job = (
Job(name="My Job")
.with_infrastructure(
DataScienceJob()
.with_storage_mount(
{
"src": "oci://<bucket>@<namespace>/<prefix>",
"dest":"test_mount_object_storage",
}
)
...
)
...
)
```
```
kind: job
spec:
infrastructure:
kind: infrastructure
spec:
...
storageMount:
- dest: test_mount_object_storage
src: oci://<bucket>@<namespace>/<prefix>
type: dataScienceJob
name: My Job
...
```
> Added support for mounting object storage service for job.

- ads/ads
- setup.py
When we install ADS to dase environment in image (PR: https://bitbucket.oci.oraclecorp.com/projects/ODSC/repos/odsc_jupyter/pull-requests/119/overview), we want to be able to run ads commands in terminal same way as we run odsc commands. This is possible with "entry_points" parameter (https://packaging.python.org/en/latest/specifications/entry-points/#entry-points).
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-42687
- changed "scripts" to "entry_points" in setup.py
- removed ads/ads file, which was used by scripts in setup.py
Reason why ads/ads removed - the ads/ads file running 2 commands:
1. assigns value to env variable, which is no longer needed, this behavior is by default after oci version older than v2.88.1: https://docs.oracle.com/en-us/iaas/tools/python/2.104.0/sdk_behaviors/ …
> ODSC-42687. Add ads entry point to invoke ads.cli:cli

- ads/jobs/builders/infrastructure/dataflow.py
- tests/unitary/default_setup/jobs/test_jobs_dataflow.py
Validation for:
- `executor_shape` and `driver_shape` must be the same shape family.
- No shape config is needed for non-flex shape
> Added validation for driver and executor shape details.

- ads/model/deployment/model_deployment.py
- ads/model/deployment/model_deployment_runtime.py
- docs/source/user_guide/model_registration/model_deploy_byoc.rst
- tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
- Added spec in `ModelDeploymentRuntime` class to support uploading large artifact
- Apply the API in `DataScienceModel` to upload artifact
```
ModelDeploymentContainerRuntime()
...
.with_model_uri("path_to_artifact")
.with_auth({"test_key":"test_value"})
.with_region("test_region")
.with_overwrite_existing_artifact(True)
.with_remove_existing_artifact(True)
.with_timeout(100)
.with_bucket_uri("test_bucket_uri")
...
```
> Support uploading large artifact for model deployment.

- ads/model/deployment/model_deployer.py
- ads/model/deployment/model_deployment.py
- ads/model/deployment/model_deployment_properties.py
- ads/model/generic_model.py
- ads/model/service/oci_datascience_model.py
- docs/source/user_guide/model_registration/model_deploy.rst
- tests/unitary/default_setup/model/test_oci_datascience_model.py
- tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
- tests/unitary/with_extras/model/test_generic_model.py
- Deprecated the use of `ModelDeploymentProperties` and `ModelDeployer` classes
- Deprecate `config`, `properties`, `model_deployment_id`, `model_deployment_url` in `ModelDeployment` constructor
- Updated the `update` API in `ModelDeployment`
- Updated the `update_deployment` API in `GenericModel`
- Updated the internal use of `ModelDeployer` and `ModelDeploymentProperties` to `ModelDeployment`
- Updated user guide
> Deprecated ModelDeploymentProperties and ModelDeployer classes

- ads/opctl/backend/ads_dataflow.py
- ads/opctl/backend/ads_ml_job.py
- ads/opctl/backend/ads_ml_pipeline.py
- ads/opctl/backend/base.py
- ads/opctl/cmds.py
- ads/opctl/decorator/__init__.py
- ads/opctl/decorator/common.py
- docs/source/user_guide/cli/opctl/_template/jobs.rst
https://jira.oci.oraclecorp.com/browse/ODSC-43375
* Adds a decorator to generate watch command for the run operation.
* Fixes the run command when it used with the existing OCID.
> [ADS OPCTL] Display prebuilt watch command for monitoring jobs with OPCTL.

- ads/opctl/backend/ads_dataflow.py
- ads/opctl/backend/ads_ml_job.py
- ads/opctl/backend/ads_ml_pipeline.py
- ads/opctl/cli.py
- tests/unitary/with_extras/opctl/test_opctl_dataflow_backend.py
- tests/unitary/with_extras/opctl/test_opctl_ml_job_backend.py
- tests/unitary/with_extras/opctl/test_opctl_ml_pipeline_backend.py
- Fixed the incorrect help information for `delete/cancel/activate/deactivate` commands
- Fixed the help information for `watch` command. 
- Added SDK supported parameters for opctl `watch` for job/data flow/pipeline
> Odsc 41744/move incorrect opctl information

- ads/common/auth.py
- ads/common/utils.py
- ads/opctl/cli.py
- ads/opctl/config/merger.py
- docs/source/user_guide/cli/authentication.rst
- tests/unitary/default_setup/auth/test_auth.py
- Added new authenticate way `security_token`
- Updated ADS SDK and OPCTL
- Updated user guide
```
import ads
ads.set_auth("security_token") # using ~/.oci/config and DEFAULT profile
ads.set_auth("security_token", profile="test_session") # using ~/.oci/config and test_session profile
ads.set_auth("security_token", oci_config_location="test_config_location", profile="test_session") # using test_config_location config and test_session profile
config = {
"region": "us-ashburn-1",
"key_file": "~/.oci/sessions/test_session/oci_api_key.pem",
"security_token_file": "~/.oci/sessions/test_session/token",
}
ads.set_auth("security_token", config=config)
with AuthContext(auth='security_token', profile="test_session"):
DataScienceJob.from_id("<job_ocid>")
singer = ads.auth.security_token()
singer = …
```
> Added support for security token authentication

- ads/feature_store/common/enums.py
- ads/feature_store/common/spark_session_singleton.py
- ads/feature_store/common/utils/feature_schema_mapper.py
- ads/feature_store/common/utils/utility.py
- ads/feature_store/docs/source/feature_group.rst
- ads/feature_store/docs/source/release_notes.rst
- ads/feature_store/docs/source/terraform.rst
- ads/feature_store/execution_strategy/spark/spark_execution.py
- ads/feature_store/feature_group_job.py
- ads/feature_store/validation_output.py
- tests/integration/feature_store/test_base.py
- tests/integration/feature_store/test_dataset_validations.py
- tests/integration/feature_store/test_datatype_pandas_array.py
- tests/integration/feature_store/test_datatype_pandas_mixed.py
- tests/integration/feature_store/test_datatype_pandas_object.py
- tests/integration/feature_store/test_datatype_spark_array_map.py
- tests/integration/feature_store/test_datatype_spark_basic.py
- tests/integration/feature_store/test_feature_group_validations.py
- tests/integration/feature_store/test_input_feature_details.py
- Convert Pandas dataframe  when its passed with with_schema_details….. and use Spark Type to Feature Type mapping
- Validate input feature details, subset
- Change FeatureType.UNKNOWN to ….FeatureType.COMPLEX for not mapped spark types
- validation output transpose
(https://teamcity.oci.oraclecorp.com/buildConfiguration/Odsc_FeatureStore_FeatureStoreAdsIntegrationTests_FeatureStoreAdsIntegrationTestsPython38/40386914?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true)
> DataType Changes, validation output transpose

- .gitleaks.toml
- .pre-commit-config.yaml
- ads/opctl/docker/Dockerfile.job
- ads/opctl/docker/Dockerfile.job.gpu
- ads/opctl/docker/base-env.yaml
- tests/unitary/with_extras/opctl/test_opctl_local_backend.py
- tests/unitary/with_extras/opctl/test_opctl_local_model_deployment_backend.py
When setup opctl testing build revealed outdated key during cuda install for jobs image gpu. This PR also includes refreshing Dockerfile.job and Dockerfile.job.gpu with recent changes in original jobs images. See ticket comments for details about original jobs images.
Setting up TeamCity to run opctl unit tests (this is not required, but for validation that TeamCity testing build runs as expected and be ready to run integration tests, when they will be ready). To make it - this PR also adds fixes to 2 test files.
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-41355
- refreshed Dockerfile.job with recent changes in original jobs image
- refreshed Dockerfile.job.gpu with recent changes in original jobs image
- fixed repo key issue for cuda installation in jpu image
- added base-enb.yaml …
> Refresh jobs images, fix key issue for cuda install, updated optcl tests

- tests/integration/feature_store/test_base.py
Prevent entity name clashes when parallel integration tests are running
> Fix test faliures

- .github/workflows/run-unittests-default_setup.yml
- .github/workflows/run-unittests.yml
This PR takes care of excluding feature store unitary tests when running with maximum dependencies as feature store requires dependencies which are only present inside the feature store conda pack. It allso adds support to trigger github workflows without creating a PR. 
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-44980
- Added new triggers for worflows: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
- Add new ignore paths in preparation for feature store merge
> ODSC-44980: Prepare workflows for feature store merge

- ads/pipeline/ads_pipeline.py
- ads/secrets/secrets.py
- setup.py
- tests/unitary/default_setup/secret/test_secretkeeper_adw.py
- tests/unitary/default_setup/secret/test_secretkeeper_auth_token.py
- tests/unitary/default_setup/secret/test_secretkeeper_bds.py
- tests/unitary/default_setup/secret/test_secretkeeper_mysqldb.py
- tests/unitary/default_setup/secret/test_secretkeeper_oracledb.py
Issue described here - https://github.com/oracle/accelerated-data-science/issues/263
- loosen pyyaml version to be >=6
```
check python ast.........................................................Passed
check docstring is first.................................................Passed
detect private key.......................................................Passed
fix end of files.........................................................Passed
pretty format json...................................(no files to check)Skipped
trim trailing …
```
> Loosen pyyaml version, which broken for latest cython.

- ads/opctl/cli.py
- Added the necessary command options for `delete\cancel\watch\activate\deactivate`:
- `--conda-pack-folder`
- `--auth`
- `--oci-profile`
- `--debug`
> Fixed opctl commands.

- ads/feature_store/docs/source/notebook.rst
1. Schema enforcement, also known as schema validation, is a safeguard in Delta Lake that ensures data quality by rejecting writes to a table that do not match the table's schema.
2. Schema evolution is a feature that allows users to easily change a table's current schema to accommodate data that is changing over time.
> added notebook for schema evolution

- ads/jobs/builders/runtimes/pytorch_runtime.py
- ads/jobs/templates/driver_pytorch.py
- tests/unitary/default_setup/jobs/test_jobs_pytorch_ddp.py
Fix two bugs for the PyTorchDistributedRuntime:
- Cast replica to string when setting it as environment variable.
- Set correct prefix for NCCL_SOCKET_IFNAME and GLOO_SOCKET_IFNAME when running DeepSpeed.
> Fix bugs for PyTorchDistributedRuntime

- ads/opctl/cli.py
- ads/opctl/cmds.py
- Fixed job run opctl command to call `run` instead of `apply` when commands like `ads opctl run --backend job ...` is passed in 
- Create and run job from YAML
- Create and run job from command parameters
> Fixed job run opctl.

- ads/opctl/cli.py
- Added the `oci_profile` and `oci_config` parameters in https://github.com/oracle/accelerated-data-science/blob/7607226fb8bccf45e8dd5a2c85a9e3af0a7cd44b/ads/opctl/cli.py#L396 so that these two parameters passed will be utilized.
> Fixed the security token issue

- ads/opctl/__init__.py
- ads/opctl/operator/cmd.py
- ads/opctl/operator/lowcode/forecast/operator.py
Replaced print statements with logger in operator folder. Removed handler from ads.opctl as it was leading to printing along with logging.
> Replaced print with logger in operator folder

- ads/hpo/ads_search_space.py
- ads/hpo/objective.py
- ads/hpo/search_cv.py
- ads/type_discovery/typed_feature.py
- setup.py
- tests/unitary/with_extras/hpo/test_hpo_search_space.py
This PR aims to upgrade the `scikit-learn` version in ads dependency. https://jira.oci.oraclecorp.com/browse/ODSC-43129
* Updated `scikit-learn` version to `>=1.0`.
* Updated `scikit-learn` 's deprecated API.
* Fixed condition check in `_extract_scoring_name()` in hpo module
* Fixed value of `criterion` used in DecisionTreeRegressor
https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html
* Fixed value of `penalty` used in SGDClassifier/Regressor
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html#sklearn-linear-model-sgdclassifier
* Test with scikit-learn==1.3.0
* Test with scikit-learn==1.2.0
* Test with scikit-learn==1.1.1
> Loosen scikit-learn version

- ads/model/generic_model.py
- The `model_deployment` property of generic model is a place holder for properties. The default runtime of it is container. After user deploys a conda runtime model and call `deploy` again, the `model_deployment` property will be updated to conda runtime, and property error happens. Though this use case is rare, but we need to cover it.
- Need to cover the following unique properties that are only available for container runtime:
-- `image`
-- `cmd`
-- `entrypoint`
-- `image_digest`
-- `server_port`
-- `health_check_port`
> Fixed generic model multiple deploy.

- ads/jobs/builders/runtimes/pytorch_runtime.py
- ads/jobs/templates/driver_pytorch.py
- ads/jobs/templates/driver_utils.py
- docs/source/user_guide/jobs/data_science_job.rst
- docs/source/user_guide/jobs/index.rst
- docs/source/user_guide/jobs/infra_and_runtime.rst
- docs/source/user_guide/jobs/run_python.rst
- docs/source/user_guide/jobs/run_pytorch_ddp.rst
- docs/source/user_guide/jobs/tabs/llama2_full.rst
- docs/source/user_guide/jobs/tabs/pytorch_ddp_torchrun.rst
- docs/source/user_guide/jobs/tabs/run_job.rst
- docs/source/user_guide/jobs/tabs/training_job.rst
- docs/source/user_guide/model_training/index.rst
- docs/source/user_guide/model_training/training_llm.rst
- docs/source/user_guide/model_training/training_with_oci.rst
- tests/unitary/default_setup/jobs/test_jobs_pytorch_ddp.py
- tests/unitary/with_extras/jobs/test_pytorch_ddp.py
Adding documentations for training LLMs with PyTorch DDP.
* Adding "Train PyTorch Models" under "Data Science Jobs" to show the APIs of `PyTorchDistributedRuntime`.
* Adding "Training Large Language Models" under "Train Models" to show an example of fine-tuning Llama2 model.
* Minor code update to `PyTorchDistributedRuntime`.
> Documentation for Training LLMs with PyTorch DDP

- ads/opctl/operator/lowcode/forecast/model/base_model.py
- ads/opctl/operator/lowcode/forecast/operator_config.py
- ads/opctl/operator/lowcode/forecast/utils.py
https://jira.oci.oraclecorp.com/browse/ODSC-46458
Added code to store Holdout Data Evaluation Metrics as metrics.csv.
Added optional parameter index in _write_data so that index can also be written if needed.
In operator_config, 
1. metrics_filename is the file name in which metrics should be stored. Set as metrics.csv by default.
2. forecast_filename is the file name in which forecasts should be stored. Set as forecast.csv by default.
> ODSC-46458/add metrics.csv

- ads/common/utils.py
- ads/jobs/builders/runtimes/base.py
- ads/jobs/builders/runtimes/python_runtime.py
- ads/opctl/backend/ads_dataflow.py
- ads/opctl/backend/ads_ml_job.py
- ads/opctl/backend/local.py
- ads/opctl/cli.py
- ads/opctl/cmds.py
- ads/opctl/operator/cmd.py
- ads/opctl/operator/common/utils.py
- ads/opctl/operator/lowcode/forecast/README.md
- ads/opctl/operator/lowcode/forecast/__init__.py
- ads/opctl/operator/lowcode/forecast/__main__.py
- ads/opctl/operator/runtime/const.py
- ads/opctl/operator/runtime/container_runtime_schema.yaml
- ads/opctl/operator/runtime/python_runtime_schema.yaml
- ads/opctl/operator/runtime/runtime.py
- pyproject.toml
- Adds supporting of the Data Flow backend for the forecasting operator.
https://jira.oci.oraclecorp.com/browse/ODSC-44202
- Improves the `ads opctl operator info -n forecast` command. The operator's `README.MD` will be used as a source of the information. The python `rich` module was utilized.
https://jira.oci.oraclecorp.com/browse/ODSC-47051
- Adds supporting of a local backend for the operators. Now the operator can be run within a local environment: ```ads opctl apply -f forecast.yaml -b operator.local```. The local environment needs to be configured before running the operator locally.
https://jira.oci.oraclecorp.com/browse/ODSC-47048
https://jira.oci.oraclecorp.com/browse/ODSC-47047
- Adds supporting of short command to run the operators. Example: ```ads opctl apply -f …
```
> ODSC-44202. Adds Data Flow + Local backends for the Forecasting operator.

- ads/opctl/operator/lowcode/forecast/environment.yaml
- pyproject.toml
* Introduces a dedicated `forecast` optional dependency group in the project.toml file. This change aims to streamline the configuration of the local environment. You can install it using the following command: `pip3 install oracle-ads[forecast]`.
* Enhances the `environment.yaml` file for the forecasting operator with the following modifications:
* Replaced the `oracle-automlx` dependency with a publicly available one.
* Added the `oracle-ads` dependency from the GitHub repository. This serves as a temporary solution until the forecasting operator becomes publicly available.
> Updates environment.yaml for the forecast operator.

- ads/opctl/decorator/common.py
- ads/opctl/operator/cmd.py
- tests/unitary/with_extras/opctl/test_opctl_decorators.py
https://jira.oci.oraclecorp.com/browse/ODSC-47201
Adds opctl environment validator decorator.
A Python decorator to validate whether a OPCTL CLI command can be executed in the current environment. This decorator will help ensure that CLI commands are only executed when the necessary conditions are met within the environment. For instance the operator's image cannot be created in the NB session or OCI Jobs.
> Adds opctl environment validator decorator.

- ads/dataset/sampled_dataset.py
ADSDataset fails without geopandas installation because its parent class PandasDataset attempts to load a file using geopandas in the constructor. The file is only used in a plot method. This PR moves the geopandas load to the plot routine where it used and adds protection so that it will only be loaded once.
There are no functionality changes.
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-47518
> Moved geopandas file load out of constructor

- ads/model/artifact_uploader.py
- ads/model/datascience_model.py
- tests/unitary/default_setup/model/test_artifact_uploader.py
https://jira.oci.oraclecorp.com/browse/ODSC-46642
Improve the [LargeArtifactUploader](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/artifact_uploader.py#L106) class to understand OCI paths to upload model artifacts to the model catalog by reference.
* Case1: user want to copy the model artifact in [ARTIFACT_PATH](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/datascience_model.py#L131) to [bucket_uri](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/datascience_model.py#L547), and then upload to MC. (this is the current case we are supporting).
* Case 2: user wants to upload model artifacts in [bucket_uri](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/datascience_model.py#L547) to MC. (this is …
> ODSC-46642/pass model by reference

- .gitleaks.toml
- docs/source/release_notes.rst
- pyproject.toml
Running release v2.8.10. Jira: ODSC-47991
- bumped version to 2.8.10
- added security_token to allowlist for pre-commit hooks
- fixed typos in pyproject.toml
```
15:41:12.598: [accelerated-data-science] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- pyproject.toml docs/source/release_notes.rst .gitleaks.toml
check python ast.....................................(no files to check)Skipped
check docstring is first.............................(no files to check)Skipped
detect …
```
> ADS release 2.8.10

- ads/jobs/ads_job.py
- ads/jobs/builders/infrastructure/dsc_job.py
- ads/opctl/backend/ads_ml_job.py
- ads/opctl/cmds.py
- tests/unitary/default_setup/jobs/test_jobs_base.py
- tests/unitary/with_extras/opctl/test_opctl_cmds.py
- Now user can cancel all job runs by calling `Job().cancel()` and `ads opctl cancel <job_ocid>`
> Added support to cancel all job runs

- ads/opctl/operator/common/errors.py
- ads/opctl/operator/common/operator_config.py
- ads/opctl/operator/lowcode/forecast/errors.py
- ads/opctl/operator/lowcode/forecast/schema.yaml
- ads/opctl/operator/lowcode/forecast/utils.py
- ads/opctl/operator/runtime/runtime.py
- Introduced OperatorSchemaYamlError, ForecastSchemaYamlError and ForecastInputDataError.
- Made target_column and target_column mandatory.
- Updated code with relevant errors.
> Extended operator errors and added forecast specific exceptions

- ads/common/dsc_file_system.py
- ads/jobs/builders/infrastructure/dsc_job.py
- tests/unitary/default_setup/jobs/test_jobs_mount_file_system.py
- Previously all file systems will be mounted under `/mnt` and now we added support for customizing the destination path in the format: `"dest" : "<destination_path>/<destination_directory_name>"`
** dir - "fss" & path - "/opc" : mount happens under "/opc/fss"
**  dir - "fss" & path - "/" : mount happens under "/fss"
** dir - "fss" & path - omitted : mount happens under "/mnt/fss" (for backward compatibility of current users)
```
infrastructure = (
DataScienceJob()
.with_log_group_id("<log_group_ocid>")
.with_log_id("<log_ocid>")
.with_storage_mount(
{
"src" : "<mount_target_ip_address>@<export_path>",
"dest" : "/test_path/test_directory_name"
}
)
)
```
The file system will be mounted to the `test_directory_name` folder under `/test_path`.
```
infrastructure = (
DataScienceJob() …
```
> Added support for customizing path for job mount file system

- ads/opctl/distributed/cli.py
The support for Ray has been added to ADS distributed training. 
https://github.com/oracle-samples/oci-data-science-ai-samples/blob/main/distributed_training/ray.md
We need to update `ads opctl distributed-training` CLI to take "ray" as a valid framework.
With this PR, users can run the following command to download the artifacts:
```
ads opctl distributed-training init --framework ray
```
```
Downloading from https://raw.githubusercontent.com/oracle-samples/oci-data-science-ai-samples/master/distributed_training/artifacts/ray_v1.tar.gz to .tmp_ray_v1.tar.gz
x ray/
x ray/v1/
x ray/v1/Dockerfile
x ray/v1/README.md
x ray/v1/__init__.py
x ray/v1/cleanup.py
x ray/v1/cleanup.sh
x ray/v1/environment.yaml
x ray/v1/ray_cluster.py
x ray/v1/run.py
x ray/v1/run.sh
x ray/v1/start-head.sh
x …
```
> Update distributed training CLI to add "ray" framework.

- ads/common/auth.py
When users passed in both `config` and `signer` in `ads.set_auth()`, the `config` is ignored and only the `signer` is used at the moment. For the use case similar to session token signer, information from the `config` is also needed.
This PR updates the behavior to use both `config` and `signer` if they are both passed into `ads.set_auth()`.
> Update `ads.set_auth()` to use both customized config and signer

- ads/opctl/operator/lowcode/forecast/model/automlx.py
Adds support for local explanation of the forecast horizon
Local explanations for a sample dataset:
- All the values are the same as the additional features have the same value in the forecast horizon, also the positive & negative values in the feature attribution represent the movement of the forecast value up/down from the mean forecast values.
> ODSC-47259 Local Explainer Class : Feature/forecast explain

- ads/model/artifact_uploader.py
- ads/model/datascience_model.py
- docs/source/user_guide/model_registration/_template/deploy.rst
- docs/source/user_guide/model_registration/_template/prepare_save_deploy.rst
- docs/source/user_guide/model_serialization/_template/prepare_save_deploy.rst
- docs/source/user_guide/model_serialization/boilerplate/deploy.rst
- docs/source/user_guide/model_serialization/boilerplate/initialize.rst
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-48247
For ads>=2.8.8, the default deployment_instance_shape set in GenericModel will depend on the following values (they are listed by following the priority, the top is the most prioritized one):
1. deployment_instance_shape value user passed in deploy()
1. shape in notebook_session_config_details
1. self.properties.shape (if the user passed ModelProperties object when initializing GenericModel )
1. environment variable if any
1. ads.model.generic_model.MODEL_DEPLOYMENT_INSTANCE_SHAPE = “VM.Standard.E4.Flex”
> ODSC-48247/Update Doc On ModelDeployment Default Shape Name Selection

- docs/source/release_notes.rst
- pyproject.toml
Running release v2.8.11. Jira: [ODSC-47991](https://jira.oci.oraclecorp.com/browse/ODSC-48360)
- bumped version to 2.8.11
- updated oci version to >=2.113.0
```
check python ast.....................................(no files to check)Skipped
check docstring is first.............................(no files to check)Skipped
detect private key.......................................................Passed
fix end of files.........................................................Passed
pretty format json...................................(no …
```
> ADS release 2.8.11

- ads/opctl/conda/cmds.py
- ads/opctl/conda/pack.py
To create and publish in one step, one could use `ads opctl conda publish` with `-f env.yaml` option. In the current implementation, we execute a `docker run` to create conda pack and a different `docker run` to export the conda pack as conda pack archive. It is noticed that in some environments, the manifest yaml is somehow not shown up upon mounting the folders in the second docker run which causes the conda pack creation to fail. 
In order to prevent this situation, we can combine the conda create and archive in the same `docker run` step. Since the create API is used idependently of publish as well, we need to provide a switch to turn on or off the conda pack archive creation. This PR is for combining the create and publish step into single docker run when user provides `-f env.yaml` …
> create archive when env yaml is provided in publish command

- ads/opctl/docker/Dockerfile.job
- ads/opctl/docker/Dockerfile.job.arm
- ads/opctl/docker/Dockerfile.job.gpu
To support arm in ads opctl we need new Dockerfile.job.arm. This PR also include minor updates in Dockerfile.job and Dockerfile.job.gpu.  Regular Dockerfile not in scope.
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-46619
- added new Dockerfile.job.arm
- set Miniconda version in Dockerfile.job
- set Miniconda version in Dockerfile.job.gpu
- removed log folder and harness setup in Dockerfile.job
```
11:32:42.136: [accelerated-data-science] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false checkout -b ODSC-46619/add_opctl_dockerfile_arm HEAD --
Switched to a new branch 'ODSC-46619/add_opctl_dockerfile_arm'
11:42:13.498: [accelerated-data-science] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -- …
```
> Add Dockerfile.job.arm to opctl

- ads/opctl/operator/lowcode/forecast/model/arima.py
- ads/opctl/operator/lowcode/forecast/model/automlx.py
- ads/opctl/operator/lowcode/forecast/model/autots.py
- ads/opctl/operator/lowcode/forecast/model/base_model.py
- ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
- ads/opctl/operator/lowcode/forecast/model/prophet.py
- ads/opctl/operator/lowcode/forecast/operator_config.py
- ads/opctl/operator/lowcode/forecast/schema.yaml
- ads/opctl/operator/lowcode/forecast/utils.py
- Reduced the number of options for the forecasting horizon and automatically infer the data frequency. [ODSC-49026](
https://jira.oci.oraclecorp.com/browse/ODSC-49026)
- Added an exception for AutoML models if the data frequency is less than one hour. [ODSC-48875](https://jira.oci.oraclecorp.com/browse/ODSC-48875)
> Reduced horizon parameters and handled datetime error for AutoMLx model

- ads/opctl/operator/lowcode/forecast/model/automlx.py
- ads/opctl/operator/lowcode/forecast/model/autots.py
- ads/opctl/operator/lowcode/forecast/model/base_model.py
- ads/opctl/operator/lowcode/forecast/model/transformations.py
- ads/opctl/operator/lowcode/forecast/utils.py
- tests/unitary/with_extras/operator/forecast/test_model_automlx.py
- tests/unitary/with_extras/operator/forecast/test_model_base_model.py
https://jira.oci.oraclecorp.com/browse/ODSC-49028
Added code to sort primary and additional data by datetime column
Added format parmater to the to_datetime function calls, so that it doesn't infer wrong format.
Added unit test for automlx on unsorted data
https://jira.oci.oraclecorp.com/browse/ODSC-48265
Added fix in evaluate_metrics function
> ODSC-49028/sort by datetime col & ODSC-48265/training metrics mismatch

- ads/opctl/operator/lowcode/forecast/model/base_model.py
- ads/opctl/operator/lowcode/forecast/utils.py
https://jira.oci.oraclecorp.com/browse/ODSC-49565
1. When test data has more values than horizon, operator fails.
2. When there is a horizon value missing for all series in test data, then test dataframe wont have that horizon. In the present code, that missing horizon is not removed from outputs so there is mismatch in the metrics calculation per horizon i.e; mismatch in the horizon picked from outputs and test data.
Changes:
outputs and test data frames should have same dates. So remove the extra dates that are not present in both test data & outputs and ensure that the dates are sorted in both dataframes so that there is no mismatch in metrics calculation.
> ODSC-49565/corrections in metrics calculation per horizon

- ads/common/oci_logging.py
The logging search function in ADS takes a sort_order argument.
- https://github.com/oracle/accelerated-data-science/blob/34661b66d9424a50cf130b7098629d0a8221d82d/ads/common/oci_logging.py#L529
- https://github.com/oracle/accelerated-data-science/blob/34661b66d9424a50cf130b7098629d0a8221d82d/ads/common/oci_logging.py#L975
The `sort_order` is applied when getting logs from the OCI logging service. However, ADS also sort the logs by `datetime` again before returning them to the user. This additional sorting is unnecessary as the logs are sorted already by the logging service.
The additional sorting makes the log search always return logs in ascending order even if the `sort_order` is set to `DESC` (default). Since multiple log record may have the same timestamp, this makes the ascending …
> Update sorting logic when getting logs from OCI logging

- docs/source/user_guide/apachespark/dataflow-spark-magic.rst
- docs/source/user_guide/configuration/authentication.rst
- docs/source/user_guide/configuration/autonomous_database.rst
- docs/source/user_guide/configuration/configuration.rst
- docs/source/user_guide/data_flow/dataflow.rst
- docs/source/user_guide/model_training/ads_tuner.rst
In the various sections of the ADS docs that relate to sample notebooks, add links to github for those sample notebooks.
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-34428
- updated 6 doc rst files with links to github for sample notebook
- fixes for issues detected by pre-commit
```
check python ast.....................................(no files to check)Skipped
check docstring is first.............................(no files to check)Skipped
detect private key.......................................................Passed
fix end of …
```
>  Update Docs to link to Github for sample notebooks

- .github/workflows/run-unittests-py38-cov-report.yml
- .github/workflows/run-unittests-py39-py310.yml
- .github/workflows/test-env-setup/action.yml
- tests/unitary/with_extras/model/test_env_info.py
- tests/unitary/with_extras/opctl/test_opctl_conda.py
Recently unit tests with optional dependencies started failing. Reason - system library install with apt-get on ubuntu failed with "E: Failed to fetch...  404  Not Found" errors. To fix we need to add apt update before using apt-get to install libkrb5-dev graphviz, which required for some of the unit tests with optional dependencies. This libraries can't be installed by pip or conda only.
Jira: no ticket
- added `apt update` before `apt-get install`
- rearranged step "Test env setup" into separate action, to avoid duplicate code
- fixed expected value in test_opctl_conda.py::TestOpctlConda::test_conda_publish 
- removed failed test_get_service_packs_cust_tenancy() as redundant one - we already testing response, which is mocked for dev tenancy - test_get_service_packs() - …
> Fix failing apt-get install in action for unit tests

- ads/jobs/serializer.py
- ads/jobs/templates/driver_utils.py
- ads/opctl/config/merger.py
- ads/opctl/utils.py
- tests/integration/jobs/test_dsc_job.py
- tests/integration/jobs/test_jobs_cli.py
- tests/integration/jobs/test_jobs_notebook.py
- tests/integration/jobs/test_jobs_notebook_runtime.py
- tests/integration/jobs/test_jobs_runs.py
- tests/integration/opctl/test_opctl_cli.py
- tests/integration/opctl/test_opctl_conda.py
- tests/integration/opctl/test_opctl_utils.py
- tests/integration/other/test_artifact_saving_data.py
- tests/integration/other/test_common_model_artifact_save.py
- tests/integration/other/test_dataflow.py
- tests/integration/other/test_dataset_factory_open.py
- tests/integration/other/test_export_generic.py
- tests/integration/other/test_hpo_tuner_artifact.py
- tests/integration/other/test_prepare_artifact.py
After we setup integration tests to run with instance principals we got 42 tests failed. This PR is to address integration tests and opctl tests. More fixes will follow in future PRs.
Jira for ALL Integration tests: https://jira.oci.oraclecorp.com/browse/ODSC-47592 (details in comments in subtasks)
Jira for OPCTL tests: https://jira.oci.oraclecorp.com/browse/ODSC-47603
In addition to code changed in the tests in this PR, there were updated done to Dynamic Groups and Policy so that instance principal will work with  logs, buckets and dataflow service.
- removed hardcoded config path from "jobs" folder
- added if to update kwargs with default_signer in jobs  serializer write_to_fle
- updated tests in "other" folder - mainly harcdoded ~/.oci/config
- fixed check-docstring-first pre-commit …
> Fix integration tests to run with instance_principal

- ads/model/deployment/model_deployment.py
- ads/model/generic_model.py
- ads/model/service/oci_datascience_model_deployment.py
- tests/unitary/default_setup/model_deployment/test_model_deployment.py
- tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
- tests/unitary/with_extras/model/test_generic_model.py
- Every time when a service error raises, log this error and return the model deployment object. The model deployment object can continue calling logging
- Raise error for model deployment that's not in `ACTIVE` state
> Fixed model deployment failed return value

- ads/opctl/config/merger.py
- ads/opctl/operator/lowcode/forecast/MLoperator
In case if the ads config not created, the ADS shows the log info:
```
".ads_ops/<backend>_config.ini does not exist. No config loaded."
```
These messages was moved on the debug level. 
Also from the forecasting operator was removed supporting dataflow backend. This can easily returned back by demand.
> ODSC-49703: Move the ADS config errors into debug level.

- ads/opctl/config/merger.py
- ads/opctl/constants.py
- ads/opctl/decorator/common.py
- ads/opctl/operator/cli.py
- ads/opctl/operator/cmd.py
- ads/opctl/operator/common/backend_factory.py
- ads/opctl/operator/common/dictionary_merger.py
- tests/unitary/with_extras/operator/test_common_dictionary_merger.py
https://jira.oci.oraclecorp.com/browse/ODSC-50353
* Allows to override the operator's config values when use ```ads operator run``` command.
```
ads operator run -f forecast.yaml -b job --spec.runtime.spec.conda.uri my_new_conda_uri --spec.infrastructure.spec.blockStorageSize 10
```
```
ads operator run -f forecast.yaml --dry-run
```
This command will show the final config that will be used to run the operator.
```
kind: operator
type: forecast
version: v1
spec:
historical_data:
url: ~/forecast/data/primary.csv
output_directory:
url: ~/forecast/result/
test_data:
url: ~/forecast/data/test.csv
model: prophet
target_column: Sales
target_category_columns:
- PPG_Code
datetime_column:
name: last_day_of_week
horizon:
periods: 4
interval: 1
interval_unit: W
report_file_name: report.html
```
``` …
```
> ODSC-50353: Allow to override the config values in the operator specification

- .github/workflows/run-unittests-py38-cov-report.yml
- .github/workflows/run-unittests-py39-py310.yml
- pyproject.toml
- test-requirements.txt
- tests/unitary/default_setup/telemetry/test_agent.py
This PR fixes several issues:
1. `ValueError: initial_types can not be detected. Please directly pass initial_types.` This error observed in model/test_model_framework_sklearn_model.py and model/test_model_framework_lightgbm_model.py. Issue is coming from https://github.com/sdpython/mlprodict/issues/488. Suggesting to fix lightgbm version <4.0.0 and relax it later when when the official releases of skl2onnx (v1.16.0) and onnxmltools (1.11.3).
2. tests hang on 99% of completion and never ends. This issue is coming from hpo tests, when they run together with whole unitary folder, tests hangs. To fix - reorganizing for tests made to run hpo tests first, and then all other
3. Some operators tests leaving behind config values, which are messing up with default values for telemetry, which …
> Fix version of lightgbm to be <4.0.0

- ads/llm/serializers/retrieval_qa.py
- docs/source/user_guide/large_language_model/index.rst
- docs/source/user_guide/large_language_model/retrieval.rst
Jira ticket: https://jira.oci.oraclecorp.com/browse/ODSC-50630
Adding documentation for the extensive support for OpenSearchVectorSearch and FAISS.
> Add vectordb deployment doc

- ads/model/deployment/model_deployment.py
- tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
- Set default logs to be both `access` and `predict` logs
- Kept streaming logs while model deployment is in `ACTIVE` state.
> Modified Watch in Model Deployment

- pyproject.toml
In September unit tests failed on fsspec version 2023.9.1 (link to failed test https://github.com/oracle/accelerated-data-science/actions/runs/6228575725/job/16905571454). Fix was to pin version fsspec <2023.9.1. Now we want to relax it.
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-50780
unit tests should pass
> Relax fsspec version

- ads/telemetry/telemetry.py
- tests/unitary/default_setup/telemetry/test_telemetry.py
https://jira.oci.oraclecorp.com/browse/ODSC-38697
Implements Telemetry decorator.
```
class MyModelDeployment:
@telemetry("plugin=mydeployer&action=deploy")
def deploy(self, name, **kwargs):
telemetry: Telemetry = kwargs.pop("telemetry", None)
if name=="mymodel":
telemetry.add("model=mymodel")
else:
telemetry.add("model=notmymodel")
...
Call the actual deployment with the appropriate signer.          
```     
The decorator exclusively alters the EXTRA_USER_AGENT_INFO environment variable, which is utilized to construct the additional_user_agent environment variable.
Without the telemetry decorator, we will retain the base telemetry settings as defined in the ```ads.auth``` module. The decorator serves the purpose of populating the api section of the telemetry.
> ODSC-38697: Implement Telemetry decorator.

- ads/model/service/oci_datascience_model_deployment.py
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-50486
Currently, the model deployment OCID shows in log when `deploy()` has been invoke. We want to print out the model deployment OCID in the notebook cell when deploy is called.
> ODSC-50486/print out model deployment id when calling predict

- ads/jobs/templates/driver_utils.py
- tests/unitary/with_extras/langchain/test_serialization.py
- tests/unitary/with_extras/langchain/test_serializers.py
The current way of saving the original LangChain's `get_type_to_cls_dict` method is not correct.
```
cls.original_type_to_cls_dict = deepcopy(llms.get_type_to_cls_dict())
```
Because `get_type_to_cls_dict` is a function but the code is saving as a dictionary.
After running this test, the subsequent calls to `get_type_to_cls_dict` will fail with
```
TypeError: 'dict' object is not callable
```
Depending on the order when running the test, some tests may appear to fail randomly due to this issue:
https://github.com/oracle/accelerated-data-science/actions/runs/7137179363/job/19453780865#step:8:3440
https://github.com/oracle/accelerated-data-science/actions/runs/7115504771/job/19371812840
Since the embedding and LLM models in this test are for serialization only without inference. There is no …
> Update LangChain Tests

- ads/catalog/model.py
When saving model to model catalog using artifacts from object storage bucket, the `UnboundLocalError` may happen if the service did not create the work request in 3 second. This could be due to a networking delay. The error is caused by local variable `new_work_request_logs` being used before assignment. This PR fixes the issue by using it only it work request logs exist.
> Fix UnboundLocalError when saving model to model catalog

- ads/model/deployment/model_deployment_infrastructure.py
- docs/source/user_guide/cli/opctl/configure.rst
- tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
- The `WEB_CONCURRENCY` is an optional parameter for model deployment service and there is no service default value for it as this value is calculated based on user's shape memory and model size.
- User can either set `WEB_CONCURRENCY` through the `with_env` in `runtime` or call `with_web_concurrency` in `infrastructure`. The latter will override the former if both methods are called.
> Updated default web concurrency value to be none

- ads/config.py
- ads/model/artifact_downloader.py
- ads/model/generic_model.py
- tests/unitary/default_setup/model/test_artifact_downloader.py
- Respected `TMPDIR` when `artifact_dir` is not provided
- Saved model artifacts directly inside the `target_dir` folder
> Updated download artifact path

- ads/model/artifact.py
- ads/model/datascience_model.py
- ads/model/generic_model.py
- tests/unitary/with_extras/model/test_generic_model.py
JIRA: https://jira.oci.oraclecorp.com/browse/ODSC-50786
The current working environment might not fit for the model it trying to loading from MD or MC. reload's failure will crash the call.  In the case of loading MD using container runtime, the message to remind user to set `ignore_conda_error=True` appears after long waiting time for loading model artifacts. 
In fact, user don't need to load the model into environment if they're not going to invoke model locally.
Not load model into environment when calling `GenericModel.from_id` by default. This will not break current user experience as when user trying to invoke model locally by `verify()`, the `reload_artifact` parameter in `verify()` is True by default. So it will reload at the time of need.
Check out …
> ODSC-50786/GenericModel: add reload options to `ModelArtifact.from_uri`

- ads/model/artifact.py
- ads/model/generic_model.py
- ads/model/runtime/env_info.py
- tests/unitary/with_extras/model/test_generic_model.py
JIRA: https://jira.oci.oraclecorp.com/browse/ODSC-50649
We currently showing the requirement of `inference_python_version` as warning message during `.prepare()`. However, user might not take any action as `.prepare()` can still work. Then `.deploy()` will fail because of this missing information.
This change aims to raise ValueError in `.prepare()` when this field cannot be resolved automatically, mandating `inference_python_version`. 
In addition, changed some warning message which could lead to misunderstanding.  For example, when user passes `inference_python_version` and the manifest of given `inference_conda_env` doesn't provide python version, the warning message will show as below:
Use debug level instead.
* `.prepare()` without `inference_python_version` and it cannot be resolved …
> ODSC-50649/raise ValueError when `inference_python_version` cannot be resolved

- .pre-commit-config.yaml
- ads/llm/chain.py
- tests/unitary/with_extras/langchain/test_guardrails.py
- tests/unitary/with_extras/langchain/test_serialization.py
- Use new [version](https://github.com/oracle-samples/oci-data-science-ai-samples/commit/1bc5270a443b791c62f634233c0f4966dfcc0dd6) of copyright checking script.
- Formatted the `.pre-commit-config.yaml` with black.
- Update LangChain serialization test to be less dependent on the LangChain version (Recent updates on LangChain added new fields).
- Update GuardrailSequence to be compatible with LangChain 0.0.353
> Update Copyright Check for 2024 and Fix LangChain tests

- ads/opctl/operator/cmd.py
- ads/opctl/operator/common/backend_factory.py
- ads/opctl/operator/common/const.py
- ads/opctl/operator/common/operator_config.py
Currently, when the merged config is generated for the operator, it contains a 'runtime' section, which can be confusing, as 'runtime' itself has its own 'runtime' section. See the example below. This PR replaces the 'runtime' section with the 'backend' section in the merged config. The resulting merged config can be used to execute operators with the `ads opctl run` command. 
The merged config enables the combination of the operator's specification and the backend configuration into a single specification file.
**Current Implementation:**
```
kind: operator
spec:
datetime_column:
name: Date
historical_data:
url: data.csv
model: auto
target_category_columns:
- Column1
target_column: target
type: forecast
version: v1
runtime:
kind: job
spec:
infrastructure:
kind: infrastructure
spec: …
```
> Renames "runtime" on the "backend" in the operator merged specification

- ads/model/artifact_downloader.py
- Non-existing `artifact_dir`
- Empty `artifact_dir`
- Existing `artifact_dir` with `force_overwrite` as False
- Existing `artifact_dir` with `force_overwrite` as True
> Fixed artifact dir

- ads/model/generic_model.py
The PR minimizes the use of repetitive strings for updating summary status by defining them as constants used by the GenericModel. The changes reflect the feedback provided in the previous PR [here](https://github.com/oracle/accelerated-data-science/pull/488#discussion_r1431934414) and [here](https://github.com/oracle/accelerated-data-science/pull/488#discussion_r1442092654). 
The PR introduces two methods, `update_summary_status` and `update_summary_action` in the GenericModel and a bunch of string constants with naming convention `STATUS_DETAIL` and `STATUS_ACTION`.
All tests in `test_generic_model.py` are ✅ .
> ODSC-34939: Cleanup Summary Status Updates

- ads/jobs/templates/driver_pytorch.py
- ads/jobs/templates/driver_utils.py
Currently, the PyTorchDistributedRuntime for Data Science Jobs is limited to `torchrun`, `deepspeed` and `accelerate` commands. This PR adds the support to allow running any command with PyTorchDistributed runtime in OCI Data Science Jobs. This will allow users to wrap the `torchrun`, `deepspeed` or `accelerate` commands with their own scripts or CLI.
> Support Running Any Command in PyTorchDistributed Runtime

- ads/opctl/operator/lowcode/forecast/schema.yaml
When we run `ads operator init -t forecast` today the resulting yaml file does not include "horizon". 
[ODSC-51509](https://jira.oci.oraclecorp.com/browse/ODSC-51509)
> Fixed horizon while generating forecast.yaml

- ads/opctl/operator/lowcode/anomaly/schema.yaml
- tests/operators/anomaly/test_anomaly_simple.py
- modified schema yaml
- updated test cases with contamination
> YAML Inputs for Anomaly Detection 

- ads/opctl/operator/lowcode/forecast/model/base_model.py
[ODSC-51508](https://jira.oci.oraclecorp.com/browse/ODSC-51508)
- Change the default output directory from "tmp_fc_operator_result" to "results"
- If the results directory already exists append by _1 & so to obtain a unique directory.
Sample run:
> [ODSC-51508] : Fix/forecast v2 for tmp folder

- ads/opctl/operator/lowcode/anomaly/model/anomaly_dataset.py
- ads/opctl/operator/lowcode/anomaly/model/automlx.py
- ads/opctl/operator/lowcode/anomaly/model/autots.py
- ads/opctl/operator/lowcode/anomaly/model/base_model.py
- ads/opctl/operator/lowcode/anomaly/model/tods.py
- ads/opctl/operator/lowcode/anomaly/utils.py
[ODSC-52180](https://jira.oci.oraclecorp.com/browse/ODSC-52180)
Right now anomaly operator supports only one target category column. Added code to support more than 1. 
Screenshots:
> Anomaly: Added support for >1 target category columns

- ads/dataset/correlation_plot.py
- pyproject.toml
- tests/unitary/default_setup/telemetry/test_agent.py
- tests/unitary/with_extras/dataset/test_dataset_correlation_plot.py
The [Bokeh](https://pypi.org/project/bokeh/) stopped supporting a python 3.7 and published a new version (3.0.0) of the package which broke ADS BokehHeatMap API.
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-35230
- added new unittests to cover BokehHeatMap class (coverage was 16% for correlation_plot.py)
- updated bokeh >=3.0.0, <3.2.0
- changed deprecated Panel model in 3.0.0 to new model - TabPanel
- removed deprecated in 3.0.0 version attribute 'render_mode' in LabelSet model
- changed deprecated attributes plot_width, plot_height to width, height
Note: removed reload of ads (it is redundant) form failed telemetry agent test. Details why in comments in Jira ticket of this bug.
```
check python ast.........................................................Passed
check docstring is …
```
> Uptake bokeh and fix ADS BokehHeatMap

- ads/aqua/base.py
- ads/aqua/extension/model_handler.py
- ads/aqua/model.py
- ads/aqua/utils.py
- ads/config.py
- tests/unitary/with_extras/aqua/test_model.py
Use query service to get models list from given compartment.
```aqua/model/?compartment_id=<OCID>```
Sample response:
```
{
"data": [
{
"name": "Mistral-7B-Instruct-v0.1-Fine-Tuned",
"id": "<OCID>",
"compartment_id": "<OCID>",
"project_id": "",
"time_created": "2024-01-19 19:33:58.078000+00:00",
"icon": "data:image/svg+xml;base64,xxxx",
"task": "text_generation",
"license": "Apache",
"organization": "Mistral AI",
"is_fine_tuned_model": true,
"tags": {...},
},
{
"name": "Llama-2-13b",
"id": "<OCID>",
"compartment_id": "<OCID>",
"project_id": "",
"time_created": "2024-01-19 17:57:39.158000+00:00",
"icon": "data:image/svg+xml;base64,xxxxx",
"task": "text_generation",
"license": "Meta license",
"tags": {...},
"organization": "Meta AI",
"is_fine_tuned_model": false
},
]
}
```
```
ads aqua …
```
> odsc-52392/list model api improvement

- ads/aqua/base.py
- ads/aqua/deployment.py
- ads/aqua/utils.py
- Added the option to load env vars from config file
- Added a static method `_load_deployment_config` shared between two methods.
- Updated docstrings
While creating a model deployment. We've added the environment variables in the deployment_config.json which looks like:
```
{
"shape": [
"BM.A10.2",
"VM.A10.2",
"BM.A10.4",
"VM.A10.4",
"VM.A100.8"
],
"environmentVariables": {
"PARAMS": "--max-model-len 1450",
"MODEL_DEPLOY_PREDICT_ENDPOINT": "/generate"
}
}
```
This structure might change as env vars might differ based on shapes.
To invoke model deployment creation, we just need 3 parameters:
```
ads aqua deployment create --model_id "ocid1.datasciencemodel.oc1.iad.xxx" --instance_shape "<shape_name>"  --display_name "<display_name>"
```
By default, server …
> Env vars added to aqua deployment 

- ads/common/oci_logging.py
- ads/common/oci_mixin.py
- ads/jobs/ads_job.py
- ads/jobs/builders/infrastructure/base.py
- ads/jobs/builders/infrastructure/dsc_job.py
- ads/jobs/builders/runtimes/base.py
- tests/unitary/with_extras/langchain/test_serialization.py
- tests/unitary/with_extras/operator/pii/test_guardrail.py
Support using custom authentication for data science jobs. With this PR, users will be able to use custom OCI authentication (`config`, `signer` and `client_kwargs`)for in the constructor of `Job`, `DataScienceJob`, and `DataScienceJobRun`. For example:
```
from ads.common import auth
from ads.jobs import Job
job = (
Job(client_kwargs={"service_endpoint": "<my_endpoint>"})
.with_infrastructure(...)
.with_runtime(...)
)
job = Job(**auth.resource_principal({"timeout": 6000}))
```
> Support using custom authentication for data science jobs

- ads/model/service/oci_datascience_model.py
I've observed that attempting to update a model already linked to a ```ModelVersionSet```, particularly when passing the same ```model_version_set_id``` as before, results in an error indicating the model is already associated with the Model Version Set.
> Exclude the model version set OCID from the model details when updating the model.

- .github/workflows/codeql.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/run-operators-unit-tests.yml
- .github/workflows/run-unittests-default_setup.yml
- .github/workflows/run-unittests-py38-cov-report.yml
- .github/workflows/run-unittests-py39-py310.yml
- tests/unitary/with_extras/langchain/test_serialization.py
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20
Jira: https://jira.oci.oraclecorp.com/browse/ODSC-52248
- updated versions in used actions for checkout, setup-python, upload-artifact, download-artifact, github-script
- fixed failed tests - copied test code for feature/aqua branch
> GitHub Actions: Transitioning from Node 16 to Node 20

- ads/jobs/builders/runtimes/base.py
- ads/jobs/templates/driver_pytorch.py
- tests/unitary/default_setup/jobs/test_jobs_pytorch_ddp.py
The distributed training uses environment variable to store the number nodes. Currently `WORLD_SIZE` is used. However, this is not really the conventional `WORLD_SIZE`. Usually `WORLD_SIZE` should be `number of nodes * number of GPUs per node`. It is better to rename `WORLD_SIZE` to `NODE_COUNT` to avoid potential confusion in the future.
> Replace WORLD_SIZE with NODE_COUNT in Distributed Training.

- ads/aqua/evaluation.py
- ads/aqua/extension/evaluation_handler.py
- ads/aqua/utils.py
- ads/jobs/builders/infrastructure/dsc_job.py
- tests/unitary/with_extras/aqua/test_evaluation.py
This PR takes care of deleting and canceling evaluations. For cancel, only the evaluation job is canceled. For delete, first we delete the job and then we delete the associated model for evaluation.
Tested deleting a job can with active Job run, that would not work with this setup. If we need to delete the job, then we should cancel the jobs run first, and then delete the job. 
- Cancel API
```
ads aqua evaluation cancel --eval_id "ocid1.datasciencemodel.oc1.iad.<OCID>"
```
Response:
```
id:              ocid1.datasciencemodel.oc1.iad.<OCID>
lifecycle_state: CANCELING
time_accepted:   2024-03-04 16:58:54.229819
INFO:ads.aqua:Canceling Job Run: ocid1.datasciencejobrun.oc1.iad.<OCID> for evaluation ocid1.datasciencemodel.oc1.iad.<OCID>
```
- Delete API
```
ads aqua evaluation delete …
```
> Cancel & Delete Evaluation

- ads/aqua/ui.py
- ads/aqua/utils.py
This PR fixes the issue where OCI passthrough apis were returning a list `[]` instead of `{data : []}`. 
The following APIs are updated:
list_log_groups
list_logs
list_logs
list_compartments
list_model_version_sets
list_buckets
list_job_shapes
list_vcn
list_subnets
> Update Passthrough api response

- ads/aqua/model.py
model list call would load all the available models in the compartment, but we want to see only active models by default. Added a check to show active models only if lifecycle_state is not set via params.
logs for when list API is called for service compartment:
```
INFO:ads.aqua:Fetch 10 model in compartment_id=ocid1.compartment.oc1..<OCID>
```
logs for when list API is called for service compartment after 2 models are deactivated
```
INFO:ads.aqua:Fetch 8 model in compartment_id=ocid1.compartment.oc1..<OCID>
```
```
============================= test session starts ==============================
collecting ... collected 1 item
test_model.py::TestAquaModel::test_list_service_models 
============================== 1 passed in 1.74s ===============================
PASSED …
```
> Keep active models by default

- ads/telemetry/base.py
- ads/telemetry/client.py
- tests/unitary/default_setup/telemetry/test_telemetry_client.py
First step to include telemetry to aqua module is to move telemetry module into ADS.
https://jira.oci.oraclecorp.com/browse/ODSC-53773
- move telemetry module from odsc_cli to ADS codebase
- builded whl
- installed it in nb-session
- run code to record event in the conda bucket (I am not sure if aqua logs created in dev)
```
from ads import set_auth
from ads.telemetry.client import TelemetryClient
set_auth("resource_principal")
AQUA_BUCKET = "service-managed-models"
AQUA_BUCKET_NS = "ociodscdev"
telemetry = TelemetryClient(bucket=AQUA_BUCKET, namespace=AQUA_BUCKET_NS)
category = "ads/telemetry/module"
action = "test"
telemetry.record_event_async(category=f"{category}", action=action)
```
- checked logs records. Saw an expected entry with. check the ticket …
> Add Telemetry module to ADS

- ads/aqua/base.py
- ads/aqua/config/container_index.json
- ads/aqua/deployment.py
- ads/aqua/utils.py
- ads/config.py
1. Return {} shapes/config for deployment and finetuning if not available in the backend.
2. For FT, look up base model name from freeform tags and get shape info for deployment.
3. If artifact_path is an OCI path, then check use it as is, else add CONDA_BUCKET_NS as namespace and service-managed-models as bucket name.
4. Set MODEL_DEPLOY_ENABLE_STREAMING as true.
> Fixes for Model Deployment

- ads/aqua/evaluation.py
A failed evaluation won't have `report.json` in its artifact. Fixing the `load_metrics` to return `report.md` only in this case.
> Fixing the loading metrics for a failed evaluation

- ads/aqua/evaluation.py
Modifies the evaluation job's runtime environment to utilize containers. Currently, the image name is hardcoded to ```iad.ocir.io/ociodscdev/odsc-llm-evaluate:0.0.2.9```.  Additional functionality is required to dynamically retrieve the latest image version for the evaluation.
> Changes the evaluation jobs runtime environment to a container-based setting.

- ads/aqua/base.py
- ads/aqua/deployment.py
- ads/aqua/utils.py
This PR adds additional logic to look up configs for fine tuning creation and deployment. If config for fine tuned models need to be looked up, then we'll use the base name instead of the model name.
> Update shapes for Fine Tuning

- ads/aqua/deployment.py
- ads/aqua/utils.py
- ads/common/utils.py
This PR adds log and log group details in the get model deployment result.
```
{
"id": "ocid1.datasciencemodeldeployment.oc1.iad.<OCID>",
"display_name": "Test deploy",
"aqua_service_model": true,
"state": "DELETED",
"description": null,
"created_on": "2024-02-06 04:31:10.684000+00:00",
"created_by": "ocid1.user.oc1..<OCID>",
"endpoint": "https://modeldeployment.us-ashburn-1.oci.customer-oci.com/ocid1.datasciencemodeldeployment.oc1.iad.<OCID>",
"console_link": "https://cloud.oracle.com/data-science/model-deployments/ocid1.datasciencemodeldeployment.oc1.iad.<OCID>?region=us-ashburn-1",
"lifecycle_details": "Model Deployment with all associated resources has been deleted",
"shape_info": {
"instance_shape": "VM.Standard.E4.Flex",
"instance_count": 1,
"ocpus": 1.0,
"memory_in_gbs": 16.0
}, …
```
> Add deployment log links in get api

- ads/aqua/exception.py
- ads/aqua/extension/base_handler.py
This PR adds default messages for error responses from the backend APIs. Also, removed a duplicate class `AquaFileNotFoundError` from the `exception.py` file.
The errors based on the user actions, and if they don't have the operation_name, then we default to status codes.
```  
"400": "Something went wrong with your request."
"403": "We're having trouble processing your request with the information provided."
"404": "Authorization Failed: The resource you're looking for isn't accessible."
"408": "Server is taking too long to response, please try again."
"500": "An error occurred while creating the resource."
"create": "Authorization Failed: Could not create resource."
"get": "Authorization Failed: The resource you're looking for isn't accessible."
```
Testing:
Create MD failed Error
```
{ …
```
> Default error message

- ads/aqua/evaluation.py
Implement method to extract and interpret exit codes from job lifecycle details.
```
_extract_job_lifecycle_details("Job run artifact execution failed with exit code 20.")
```
```
"The destination folder does not exist or cannot be accessed for writing. Please verify the folder's existence and permissions."
```
> Implement method to extract and interpret exit codes from job lifecycle details

- ads/aqua/config/container_index.json
- ads/aqua/deployment.py
- ads/aqua/evaluation.py
- ads/aqua/utils.py
1. Add new evaluation and deployment images
2. Update get_container_image to take in only key and config file
3. Use latest container image for evaluation from index file
Testing:
Note: ocid and namespace has been hidden.
Create MD Logs
```
INFO:root:Env vars used for deploying ocid1.datasciencemodel.oc1.iad.<OCID>:{'BASE_MODEL': 'aqua/models/falcon-7b', 'PARAMS': '--served-model-name odsc-llm', 'MODEL_DEPLOY_PREDICT_ENDPOINT': '/v1/completions', 'MODEL_DEPLOY_ENABLE_STREAMING': 'true'}
INFO:root:Aqua Image used for deploying ocid1.datasciencemodel.oc1.iad.<OCID> : iad.ocir.io/<namespace>/odsc-vllm-serving:0.3.0.3
```
Create Eval Logs
```
INFO:ads.aqua:Aqua Image used for evaluating ocid1.datasciencemodeldeployment.oc1.iad.<OCID> …
```
> Update container index with new images

- ads/common/object_storage_details.py
- ads/model/artifact_downloader.py
- ads/model/datascience_model.py
- tests/unitary/default_setup/model/test_artifact_downloader.py
- tests/unitary/default_setup/model/test_datascience_model.py
1. change `artifact` property to be set either as a string or a list using an iterable.
2. For Large Artifact Downloader with model by reference, set bucket_uri as None as artifact will be downloaded using model_file_description.
3. For model by reference, files are saved locally at `target_dir/bucket_name/file_name_with_prefix`.
1. Creating model with multiple artifact location
```
artifact_path = "oci://service-bucket@namespace/model_path"
weights_path = "oci://user-bucket@namespace/weights_path"
model = (DataScienceModel()
.with_compartment_id(compartment_id)
.with_project_id(project_id)
.with_display_name(MODEL_NAME)
.with_artifact(artifact_path, weights_path)
)
model.create(model_by_reference=True,)
model.download_artifact(target_dir="artifact_dir")
``` …
> Model by reference for Multiple Models

- ads/aqua/model.py
- ads/model/datascience_model.py
- tests/unitary/default_setup/model/test_datascience_model.py
- If model_file_description is available, the user don't need to pass artifact using `with_artifact` when creating a model by reference.
1. Creating model with artifact location
```
artifact_path = "oci://service-bucket@namespace/model_path"
model = (DataScienceModel()
.with_compartment_id(compartment_id)
.with_project_id(project_id)
.with_display_name(MODEL_NAME)
.with_artifact(artifact_path)
)
model.create(model_by_reference=True,)
```
2. Creating model with model_file_description
```
model = DataScienceModel.from_id("ocid1.datasciencemodel.oc1.iad.<OCID>")
model_file_description = model.model_file_description
model = (DataScienceModel()
.with_compartment_id(compartment_id)
.with_project_id(project_id)
.with_display_name(MODEL_NAME) …
```
> Ignore artifact when model file description is available during model creation

- ads/aqua/config/resource_limit_names.json
- ads/aqua/extension/ui_handler.py
- ads/aqua/ui.py
- ads/common/oci_client.py
- ads/config.py
This PR adds an API to get shapes availability before the user tries to create a deployment (can be used for Fine tuning as well).
1. Get shapes (unavailable)
```
http://localhost:8888/aqua/shapes/limit?instance_shape=VM.GPU.A10.2
```
Response
```
{
"status": 403,
"message": "We're having trouble processing your request with the information provided.",
"service_payload": {
"available_count": 0
},
"reason": "Inadequate resources are available to create the BM.GPU.A100-v2.8 resource. The number of available resources associated with the limit name ds-gpu-a100-v2-count are 0.",
"request_id": "3cf5643c-222d-4e13-a5af-ce16a3148ab7"
}
```
2. Get shapes (available)
```
http://localhost:8888/aqua/shapes/limit?instance_shape=VM.GPU.A10.2
```
Response
```
{
"available_count": 24
}
```
> Get shapes availability API

- ads/aqua/model.py
- ads/aqua/training/__init__.py
- ads/aqua/training/exceptions.py
- tests/unitary/with_extras/aqua/test_finetuning.py
Show lifecycle status details based on the job run exit code. The exit code mappings are obtained from the `exceptions.py`.
The `exceptions.py` is the same file from the fine-tuning package and it is used for raising the exceptions.
In the future, the fine-tuning package can import this file from ADS.
> Show lifecycle status message base on Fine-tuning job exit code.

- ads/aqua/model.py
- ads/aqua/utils.py
Add  `ready_to_deploy` in the response format of LIST Models and GET Model
service models will always have ready_to_deploy=True
For custom models, the value of `OCI_AQUA` tag will be `ACTIVE` if it is ready for deployment.
```
GET http://localhost:8888/aqua/model/<model_ocid>
GET http://localhost:8888/aqua/model/
GET http://localhost:8890/aqua/model/?compartment_id=<ocid>
```
> Add `ready_to_deploy` in model's attributes

- ads/aqua/extension/ui_handler.py
- ads/aqua/ui.py
This PR adds an API to check if the user bucket is versioned.
1. Versioned bucket
```
http://localhost:8888/aqua/bucket/versioning?bucket_uri=oci://versioned-bucket-name@<namespace>/prefix/
```
Response
```
{
"is_versioned": true,
"message": "Model artifact bucket oci://versioned-bucket-name@<namespace>/prefix/ is versioned."
}
```
2. Unversioned bucket
```
http://localhost:8888/aqua/bucket/versioning?bucket_uri=oci://unversioned-bucket-name@<namespace>/prefix/
```
Response
```
{
"is_versioned": false,
"message": "Model artifact bucket oci://unversioned-bucket-name@<namespace>/prefix/ is not versioned. Check if the path exists and enable versioning on the bucket to proceed with model creation."
}
```
3. Bucket does not exist
```
http://localhost:8888/aqua/bucket/versioning?bucket_uri=oci:/ …
```
> Bucket versioning check API

- ads/aqua/finetune.py
This would help understanding how the different shape and replica combinations are used for specific models.
Also the last a few characters of the OCID is saved so that we might use it to match with other telemetry records (in the future).
> Telemetry: Track shape name, replica and ocid along with the model.

- ads/aqua/evaluation.py
- ads/aqua/extension/finetune_handler.py
- ads/aqua/utils.py
- tests/unitary/with_extras/aqua/test_evaluation.py
This PR contains improvements on the following APIs:
* List eval
* Get status
* Fix the logic for determine termination state
* Add cache for evaluation in terminal state
* Still use rqs to get each jobrun but use threadpool with 10 threads and send all possible requests in parallel
```
GET http://localhost:8888/aqua/evaluation
```
> Evaluation APIs Improvements

- ads/aqua/extension/ui_handler.py
- ads/aqua/ui.py
This PR gives an option to list versioned bucket when calling list bucket API.
To list versioned buckets, call:
```
http://localhost:8888/aqua/buckets/?versioned=true
http://localhost:8888/aqua/buckets/?versioned=True
```
For any other value of versioned or if versioned is not set, then all buckets will be listed.
This API uses Threadpoolexecutor to to check for bucket versions in parallel, with workers set to 10.
> Bucket list with versioning check

- ads/aqua/model.py
- ads/aqua/utils.py
aqua utils.py has it's own CONDA_BUCKET_NS constant without any default value, will fail APIs when not set. We'll use the existing one from ads.config instead.
> Conda bucket env var update

- .github/workflows/run-unittests-default_setup.yml
- .github/workflows/run-unittests-py38-cov-report.yml
- .github/workflows/run-unittests-py39-py310.yml
- .github/workflows/test-env-setup/action.yml
- README-development.md
- dev-requirements.txt
- pyproject.toml
- test-requirements.txt
We want to relax pandas constraint in ADS dependency list. This has to be >2.2.0 for python 3.9+. Lower compatible version for python3.8. The work includes fixating other dependency versions and moving pii tests to python3.8 tests pipeline only. pii module wont' be compatible with pandas 2.2.0 in py3.9+, because of 'datapane' pandas restriction - https://github.com/datapane/datapane/blob/main/python-client/pyproject.toml#L46C10-L46C26.
During this work revealed an issue that our test pipelines were not setting up py3.8, py3.9 and py3.10 test envs correctly. In this PR there is a fix for pipelines also.
Also observed that time for creating testing env in for py3.9/py3.10 drastically increasing when broad version restriction. Pip downloading all possible versions to later resolve. I …
> [to main branch] Pandas uptake for py3.8 and py3.9+

- ads/aqua/exception.py
- ads/aqua/extension/base_handler.py
- ads/aqua/ui.py
If user does not have access to list shape availability, we'll now show the following error message:
```
{
"status": 404,
"message": "Authorization Failed: The resource you're looking for isn't accessible. Operation name: get_resource_availability",
"service_payload": {},
"reason": "Could not check limits availability for the shape VM.GPU.A10.1",
"request_id": "56ce00a4-a530-428d-b483-853b487a0586"
}
```
> Shapes limit error handling

- ads/aqua/ui.py
Updated limit check message based on feedback from Product team.
```
{
"status": 404,
"message": "Authorization Failed: The resource you're looking for isn't accessible. Operation Name: get_resource_availability.",
"service_payload": {
...
}
"reason": "Could not check limits availability for the shape VM.GPU.A10.1. Make sure you have the necessary policy to check limits availability.",
...
}
```
> Update limits message

- ads/model/datascience_model.py
- tests/unitary/default_setup/model/test_datascience_model.py
This PR skips version check on service model bucket for aqua.
> Remove service bucket version check

- ads/aqua/data.py
- ads/aqua/finetune.py
- ads/aqua/model.py
- ads/aqua/utils.py
* Send ready_to_finetune info for List/Get models.
* Extracts ready_to_deploy info from tag `OCI_AQUA` for service model. 
* Checking custom models
* Checking service models
> Add ready_to_finetune info

- ads/aqua/config/compartment_mapping.json
- ads/config.py
- Load ODSC_MODEL_COMPARTMENT_OCID constant from config file, else default to env var.
- remove unused constants - AQUA_MODEL_DEPLOYMENT_IMAGE
> Load compartments from mapping file

- ads/aqua/__init__.py
- ads/aqua/extension/common_handler.py
- ads/aqua/model.py
- ads/aqua/utils.py
- ads/config.py
- tests/unitary/with_extras/aqua/test_model.py
Compartment mapping will now be loaded from container_index.json.
```
{
"odsc-llm-evaluate": [
{
"name": "dsmc://odsc-llm-evaluate",
"version": "x.x.x"
}
],
"odsc-llm-fine-tuning": [
{
"name": "dsmc://odsc-llm-fine-tuning",
"version": "x.x.x"
}
],
"odsc-vllm-serving": [
{
"name": "dsmc://odsc-vllm-serving",
"version": "x.x.x"
}
],
"service-model-compartment": {
"namespace1": "ocid1.compartment.oc1..<OCID>",
"namespace2": "ocid1.compartment.oc1..<OCID>"
}
}
```
> Compatibility check for Aqua extension and update compartment mapping config

- tests/unitary/with_extras/aqua/test_evaluation_handler.py
- tests/unitary/with_extras/aqua/test_handlers.py
- tests/unitary/with_extras/aqua/utils.py
This PR aims to add tests for aqua handlers
> Add test cases for handlers: Evaluation/Common/Base

- ads/catalog/model.py
- ads/catalog/notebook.py
- ads/catalog/project.py
- ads/catalog/summary.py
- ads/data_labeling/metadata.py
- ads/dataset/dataset.py
- ads/dataset/factory.py
- ads/dataset/sampled_dataset.py
ADSDataset.show_in_notebook fails while rendering visualizations.
When user tries to run ds.show_in_notebook() when trying to print visualizations in a notebook, they get the following error:
```
ERROR - Exception
Traceback (most recent call last):
File "/apps/mambaforge/envs/jupyter/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "/tmp/ipykernel_11835/2876128834.py", line 1, in <cell line: 0>
ds.show_in_notebook()
File "/apps/mambaforge/envs/jupyter/lib/python3.11/site-packages/ads/common/decorator/runtime_dependency.py", line 174, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/apps/mambaforge/envs/jupyter/lib/python3.11/site-packages/ads/common/decorator/runtime_dependency. …
```
> ADSDataset.show_in_notebook fails while rendering visualizations

- ads/aqua/extension/base_handler.py
- tests/unitary/with_extras/aqua/test_handlers.py
When OCI create operation fails, the message returned to the user is "Authorization Failed: Could not create resource." This does not convey why the failure occurred, hence we add the operation name to this message to determine the exact operation failure.   
The get method already has this, the one for create was missing.
```
> python3 -m pytest tests/unitary/with_extras/aqua/test_handlers.py
===================================================== test session starts ======================================================
platform darwin -- Python 3.8.18, pytest-7.4.0, pluggy-1.0.0 -- /Users/vmascarenhas/miniconda3/envs/ads-local-v38/bin/python3
rootdir: /Users/vmascarenhas/workspace/git/accelerated-data-science
plugins: Faker-24.9.0, …
```
> Update error message for create method failure

- tests/unitary/with_extras/aqua/test_data/valid_eval_artifact/report.html
- tests/unitary/with_extras/aqua/test_evaluation.py
Add test case for evaluation download_report based on the finding from investigating evaluation report rendering error. Validating that special character can also be handled well.
> Add test cases for checking content decoding

- ads/aqua/evaluation.py
- test-requirements.txt
- tests/unitary/with_extras/aqua/test_evaluation.py
This PR aims to fix the following problem:
* potential NPE
* AttributeError cannot be caught correctly
> bugfix/aqua.evaluation 

- ads/aqua/deployment.py
- ads/aqua/evaluation.py
- ads/aqua/finetune.py
Telemetry data related to shape model combination for MD and finetune has a bad design so that visualized report not easily build out for this metrics. Suggesting an update, so that we will do:
```
aqua/custom/deployment/create/shape/{shape}
{value=model_name}
aqua/service/deployment/create/shape/{shape}
{value=model_name}
aqua/service/finetune/create/shape/{shape}
{value=model_name}
```
instead:
```
aqua/custom/{model_name}/deployment/create/shape/{shape}
aqua/service/{model_name}/deployment/create/shape/{shape}
aqua/service/{model_name}/finetune/create/shape/{shape}
```
Also dropping:
```aqua/service/deployment/create/shape/{shape}```, this will duplicate suggested change above, if used without value
```aqua/custom/deployment/create/shape/{shape}```, this will duplicate suggested change …
> Fix telemetry event record to better report output

- ads/aqua/finetune.py
In certain datasets, the packing of dataset can cause failure during Fine Tuning. By allowing for turning off this option, we can unblock the cases where this occurs. We will enable only CLI for now. We can add more options on UI under advanced section.
We have to move batch_size to AquaFineTuningParms class. 
We also need a method on the dataclass that can automatically turn the parameters to cmd arguments and avoid hard-coding.
Usage - 
```
ads aqua fine_tuning create \
--ft_source_id $(MODEL_SOURCE) \
--ft_name $(NAME)-FT \
--dataset_path  $(DATASET)\
--report_path $(OUTPUT) \
--ft_parameters '{"epochs": $(EPOCH), "learning_rate": 0.0002, "sample_packing": "$(SMP_PKG)"}' \
--shape_name $(SHAPE) \
--replica $(REPLICA) \
--validation_set_size 0.1 \
--subnet_id $(SUBNET)\
--log_group_id …
```
> Ability to disable packing of dataset in CLI

- pyproject.toml
- Upgraded oci version to [2.125.3](https://github.com/oracle/oci-python-sdk/releases/tag/v2.125.3)
> Upgraded oci version to support md custom egress.

- ads/aqua/deployment.py
- ads/aqua/utils.py
Added util function as per [review comments](https://github.com/oracle/accelerated-data-science/pull/803#discussion_r1578210330).
> Add substring util

- ads/model/model_metadata.py
- tests/unitary/default_setup/model/test_model_metadata.py
Improves the extraction of custom metadata items by key.
now it supports providing a value to return if the specified key does not exist.
```
assert metadata.get("NoneExistingKey", None) == None
```
> Improves the extraction of custom metadata items by key.

- ads/aqua/cli.py
- ads/aqua/exception.py
- ads/cli.py
- tests/unitary/with_extras/aqua/test_cli.py
This PR aims to:
* provide the --verbose and --debug flag to set aqua logging level to `INFO` and `DEBUG` respectively.
* Improve CLI error handling: gracefully exit when encounter error.
* Improve CLI test
```
ads aqua model get <ocid> --verbose
ads aqua model get <ocid> --debug
```
If user provide two flags together, it will no proceed. e.g.:
```
ads aqua model get <ocid> --debug --verbose
>>> ERROR:ads:Cannot use `--debug` and `--verbose` at the same time. Please select either `--debug` for `DEBUG` level logging or `--verbose` for `INFO` level logging.
```
When user explicitly use --verbose/--debug flag, CLI will take the flag to set the logging level. `--log-level` can be use without --verbose/--debug.
Define exit_code for each AquaError. We need to have a table to show the mapping …
> AQUA CLI: Improve handling error and Add new flags 

- ads/jobs/builders/infrastructure/dsc_job.py
- tests/unitary/default_setup/jobs/test_jobs_run.py
This PR adds the following for job run:
- `wait()` method, which will wait until the job run finishes without printing the logs (while `watch()`) prints the logs.
- `exit_code` property, which extracts the exit code from the lifecycle details.
- `force_delete` option to the `delete()` method, which will cancel the job run when it is set to `True`.
This PR also fixes the bug that `force_delete` is available in job.delete() but it is not actually used.
> Updates on Job Run API

- ads/aqua/evaluation.py
- tests/unitary/with_extras/aqua/test_evaluation.py
This PR aims to fix status for DELETING/DELETED evaluation:
* Improved `_get_status` to return correct status under different cases.
* DELETE Eval will return the real status if can be fetched or `DELETING` if real status not available. 
* DELETE Eval remove target eval from listing cache, so that when UI invoke LIST can get correct status. 
* UI show banner/or something else that deletion in progress while waiting for backend response.
> Odsc-56003/fix eval delete

- ads/aqua/constants.py
- ads/aqua/deployment.py
- ads/aqua/model.py
- ads/aqua/utils.py
- tests/unitary/with_extras/aqua/test_model.py
* Added Test cases for import model
* Changed logic around setting deployment container default command line options and the default environment variables. This information will be extracted from the container_index.json. This will allow us for adding multiple inference containers, without having to change the code
Minor fixes -
* Deployment requires only BASE_MODEL env variable
* Changed the return type for register API to return DataScienceModel
* Auto inferencing of service managed container type from the container URI
> test cases for import models

- ads/model/datascience_model.py
When loading DataScienceModel from yaml, the model_file_description attribute remains empty since the attribute map value is incorrect. There were no breaking changes before as this property was set when create() is called. 
This PR updates the attribute mapping value from `model_file_description` to `model_description`, without updating the property name.
```
yaml_model = DataScienceModel.from_yaml(uri="tests/unitary/with_extras/aqua/test_data/deployment/aqua_finetuned_model.yaml")
print(yaml_model.model_file_description)
{'models': [{'bucketName': 'service-managed-models',
'namespace': 'namespace',
'objects': [{'name': 'service_models/model-name/commit-id/artifact/README.md',
'sizeInBytes': 3836,
'version': '5707cfc1-499b-4ce0-aeec-32e2336c5195'},
{'name': …
```
> Update model description attribute map

- ads/aqua/constants.py
- ads/aqua/data.py
- ads/aqua/model.py
- tests/unitary/with_extras/aqua/test_model.py
1. Adds ready_to_import to `AquaModelSummary` that is set as True if  the models in the service compartments have the freeform tag `ready_to_import :  true`. 
2. create() model fails if project and compartment id are not set, updated the code since tests were failing. This might be changed later on to accommodate user provided compartment and project id as parameters.
List Imported Models API - [ODSC-56561](https://jira.oci.oraclecorp.com/browse/ODSC-56561)
Shadow models data setup - [ODSC-56857](https://jira.oci.oraclecorp.com/browse/ODSC-56857)
The Phi-3-mini-128k-instruct added to the service compartment with ready_to_import freeform tag set ass true, whereas the others would not have this tag. 
`http://localhost:8888/aqua/model`
```
{
"data": [
{ …
```
> Add ready_to_import for list API

- ads/aqua/extension/common_handler.py
- ads/aqua/extension/model_handler.py
- ads/aqua/model.py
- tests/unitary/with_extras/aqua/test_model_handler.py
https://jira.oci.oraclecorp.com/browse/ODSC-56763
https://jira.oci.oraclecorp.com/browse/ODSC-56565
**Implements:**
- [BYOM][API] Check Internet Access.
- [BYOM][API] Fetch HF Model Details.
```
http://localhost:8888/aqua/network_status
```
```
http://localhost:8888/aqua/model/hf/search
```
BODY
```
{
"model_id": "codellama/CodeLlama-7b-Instruct-hf"
}
```
NEGATIVE
> AQUA Fetch HF Model Details

- ads/aqua/data.py
- ads/aqua/deployment.py
- ads/aqua/extension/deployment_handler.py
- tests/unitary/with_extras/aqua/test_deployment.py
This PR covers the code changes to return a list of deployment parameters from the deployment_config.json. The validation of these parameters prior to model deployment will be covered in a separate PR.
For the below test config file
```
{
"shape": [
"VM.GPU.A10.1"
],
"configuration": {
"VM.GPU.A10.1": {
"parameters": {
"VLLM_PARAMS": "--max-model-len 4096 --seed 42 --trust-remote-code"
}
}
}
}
```
```
http://localhost:8888/aqua/deployments/ocid1.datasciencemodel.oc1.iad.<ocid>/params?instance_shape=VM.GPU.A10.1
```
```
{
"data": [
"--max-model-len 4096", "--seed 42", "--trust-remote-code"
]
}
```
```
> python -m pytest tests/unitary/with_extras/aqua/test_deployment.py -k "test_get_deployment_default_params"
========================================= test session starts …
```
> Get default configurations for Model Deployment

- ads/aqua/model.py
- tests/unitary/with_extras/aqua/test_model.py
* Load Readme.md from artifact_location/config for shadow models else read from artifact location
* Minor fixes on setting tags for imported model
> Modelcard for shadow models

- ads/aqua/extension/finetune_handler.py
- ads/aqua/finetune.py
- tests/unitary/with_extras/aqua/test_data/finetuning/ft_config.json
- tests/unitary/with_extras/aqua/test_finetuning.py
- tests/unitary/with_extras/aqua/test_finetuning_handler.py
This PR is built on top of changes made in [PR-827](https://github.com/oracle/accelerated-data-science/pull/827). 
We add a new API that returns the default params used for a fine tuning job. These params are read from ft_config.json but only those that are available in `AquaFineTuningParams` dataclass will be made available to the user. 
```
http://localhost:8888/aqua/finetuning/ocid1.datasciencemodel.oc1.iad.<ocid>/params
```
```
{
"data": [
"--batch_size 1",
"--sequence_len 2048",
"--sample_packing true",
"--pad_to_sequence_len true",
"--learning_rate 0.0002",
"--lora_r 32",
"--lora_alpha 16",
"--lora_dropout 0.05",
"--lora_target_linear true",
"--lora_target_modules q_proj,k_proj"
]
}
```
If ft_config.json is not available for the given model is, then the response will be:
```
{ …
```
> Get default configurations for Model FineTuning

- ads/aqua/extension/model_handler.py
- ads/aqua/model.py
- tests/unitary/with_extras/aqua/test_model_handler.py
The list and get API were failing due to a couple reasons:
1. model_type was passed as kwargs, which would be passed along to the datascience client's list_models API  when compartment id is not set. This would fail as this param is not an acceptable param for list_models as keyword args. 
2. is_shadow_type was defined after it was used, and aqua_model_attributes variable had a typo.
We now add a new param model_type to list_api instead of passing as kwargs. 
```
========================================= test session starts ==========================================
plugins: …
```
> Update get and list model API

- tests/unitary/with_extras/aqua/test_data/ui/container_index.json
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_ui_handler.py
UI Handler Unit test are failing on GH although they work fine locally. The error isn't evident as the tests are timing out before errors get printed. Testing the changes in this PR to check if the way we patch the mocks are causing any issue.
Also, a couple deployment tests were failing due to an additional config file loaded during creation. This has been fixed in this PR.
```
> python -m pytest -q tests/unitary/with_extras/aqua/test_ui_handler.py
========================================= test session starts ==========================================
collected 14 items …
```
> Fix UI handler and deployment tests

- ads/aqua/finetuning/finetuning.py
- ads/aqua/modeldeployment/deployment.py
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_finetuning.py
Instead of returning a list of string parameters, the default FT params are returned as a dict. This ensures that UI does not have to understand the param type and validation becomes easier as well.
```
http://localhost:8888/aqua/finetuning/ocid1.datasciencemodel.oc1.iad.<ocid>/params
```
```
{
"params": {
"batch_size": 1,
"sequence_len": 2048,
"sample_packing": true,
"pad_to_sequence_len": true,
"learning_rate": 0.0002,
"lora_r": 32,
"lora_alpha": 16,
"lora_dropout": 0.05,
"lora_target_linear": true,
"lora_target_modules": [
"q_proj",
"k_proj"
]
}
}
```
```
> python -m pytest -q tests/unitary/with_extras/aqua/test_finetuning.py
========================================= test session starts ==========================================
platform darwin -- Python 3.8.18, pytest-7.4.0, …
```
> Finetuning and MD default params dict

- ads/aqua/extension/model_handler.py
- ads/aqua/model/model.py
- tests/unitary/with_extras/aqua/test_model.py
1. Adds a `pipeline_tag` check as the API fails where this tag is None.
2. Add AQUA_SERVICE_MODEL_TAG with source model id as value when registered models are verified.
```
rootdir: /Users/vmascarenhas/workspace/git/accelerated-data-science
collected 16 items
tests/unitary/with_extras/aqua/test_model.py ................                                                          [100%]
===================================================== 16 passed in …
```
> Add source model tag to imported models

- ads/aqua/extension/model_handler.py
- ads/aqua/model/model.py
- tests/unitary/with_extras/aqua/test_model.py
1. Rename shadow models to verified models.
2. use model_name instead of base path name for registered models.
3. Remove `local_dir_use_symlinks` param while downloading model from huggingface.
4. Remove `inference_container` check when registered models.
5. Remove unused imports.
```
collected 16 items
tests/unitary/with_extras/aqua/test_model.py ................ …
```
> Minor changes for Verified Models

- ads/aqua/model/model.py
- pyproject.toml
- tests/unitary/with_extras/aqua/test_model.py
This PR fixes the huggingface-hub version to 0.22.2 in ads. We can remove `local_dir_use_symlinks` reference from ads once huggingface-hub is updated to 0.23.*.
```
collected 16 items
tests/unitary/with_extras/aqua/test_model.py ................                                                          [100%]
===================================================== 16 passed in 2.04s …
```
> Fix version of HF hub in ads

- ads/aqua/common/enums.py
- ads/aqua/extension/base_handler.py
- ads/aqua/extension/deployment_handler.py
- ads/aqua/extension/errors.py
- ads/aqua/extension/evaluation_handler.py
- ads/aqua/extension/finetune_handler.py
- ads/aqua/extension/model_handler.py
- ads/aqua/extension/ui_handler.py
- ads/aqua/extension/utils.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
- tests/unitary/with_extras/aqua/test_evaluation_handler.py
1. Move Error class from `ads/aqua/extension/base_handler.py` to `ads/aqua/extension/errors.py`. 
2. Remove duplicate DataScienceResource enum in `ads/aqua/common/enums.py`.
```
> python -m pytest -q tests/unitary/with_extras/aqua/test_*handler.py
collected 56 items
tests/unitary/with_extras/aqua/test_common_handler.py ...                                                              [  5%]
tests/unitary/with_extras/aqua/test_deployment_handler.py ..s..... …
```
> Refactor base handler

- ads/aqua/common/utils.py
- ads/aqua/constants.py
- ads/aqua/evaluation/evaluation.py
- ads/aqua/model/model.py
- tests/unitary/with_extras/aqua/test_model.py
1. CONSOLE_LINK_RESOURCE_TYPE_MAPPING was missing in utils.py after code refactor.
2. is_valid_ocid now checks if input begins with ocid instead of regex check.
3. If container_index is not accessible, then print debug logs instead of error.
4. `copy_model_config` util function added which copies config json from artifact path of verified models to user bucket.
```
collected 17 items …
```
> Copy verified configs for imported models

- ads/aqua/common/utils.py
- tests/unitary/with_extras/aqua/test_model.py
Adding a --no-overwrite flag to the `oci os bulk-upload` command to avoid asking for user input when the file was already uploaded to the location.
> skip prompt when file is already uploaded to os

- ads/aqua/extension/model_handler.py
- tests/unitary/with_extras/aqua/test_model_handler.py
This update improves the error message displayed by Hugging Face when searching for a model.
```
{
"status": 400,
"message": "Something went wrong with your request.",
"service_payload": {
"error": "RepositoryNotFoundError"
},
"reason": "Failed to access `https://huggingface.co/api/models/codellama/CodeLlama-7b-Instruct-hf_err.`. Please check if the provided repository name is correct. If the repo is private, make sure you are authenticated and have a valid HF token registered. To register your token, run this command in your terminal: `huggingface-cli login`",
"request_id": "b5d25729-b38c-4fc0-91f4-63f2d34c32df"
}
```
> AQUA. Enhance error message generated by HF.

- ads/aqua/config/config.py
- ads/aqua/finetuning/finetuning.py
- tests/unitary/with_extras/aqua/test_finetuning.py
This PR covers the following changes:
1. Add default configuration for Finetuning for unverified models
2. Update FT parameters validation API to accept dict instead of string params to avoid double conversion on the UI side.
1. FT default config API
` GET http://localhost:8888/aqua/finetuning/config/ocid1.datasciencemodel.oc1.iad.<unverified-model-ocid>`
```
{
"shape": {
"VM.GPU.A10.1": {
"batch_size": 1,
"replica": "1-10"
},
"VM.GPU.A10.2": {
"batch_size": 1,
"replica": "1-10"
},
"BM.GPU.A10.4": {
"batch_size": 1,
"replica": 1
},
"BM.GPU4.8": {
"batch_size": 4,
"replica": 1
},
"BM.GPU.A100-v2.8": {
"batch_size": 6,
"replica": 1
}
}
}
```
2. FT param validation API
```
POST http://localhost:8888/aqua/finetuning/params
{
"params": {
"learning_rate": 0.0002,
"batch_size": 1, …
```
> Set default FT configs for unverified models and update validation API

- ads/aqua/common/enums.py
- ads/aqua/extension/deployment_handler.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/constants.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/enums.py
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
This PR includes the changes for:
1. When user registers the model and inference container is not set, then set default as `odsc-tgi-serving`.
2. When deployment is created, accept container_family as input when user deploys unverified models. 
3. When model params are being validated, accept container_family as input when user validates params for unverified models.
```
> python -m pytest -q tests/unitary/with_extras/aqua/test_deployment*.py
collected 29 items …
```
> Accept container family as input for model creation and param validation

- ads/aqua/extension/common_handler.py
- ads/aqua/extension/model_handler.py
Adds ```/aqua/hf_login``` POST handler to login to HF.
```
{
"token": "your_token_here"
}
```
The ```/aqua/model/hf/search``` handler was extended with the ```token``` parameter. 
```
{
"model_id": "mistralai/Mistral-7B-Instruct-v0.2",
"token": "your_token_here"
}
```
> AQUA. Adds HF Login handler.

- ads/opctl/operator/lowcode/forecast/model/ml_forecast.py
Recently added MLforecast model was not using the datetime column from the spec.
> Bug: mlforecast not taking datetime column from the spec

- ads/aqua/modeldeployment/constants.py
This PR adds more parameters that are restricted to be overridden by the user. Some params like "served-model-name", "seed", "sharded", "trust-remote-code" are already disallowed by in the backed as they're present in container_index.json, we'll add them here as well for reference.
```
> python -m pytest -q tests/unitary/with_extras/aqua/test_model*.py
=================================== test session starts ===================================
collected 24 items
tests/unitary/with_extras/aqua/test_model.py .................                      [ 70%]
tests/unitary/with_extras/aqua/test_model_handler.py ....... …
```
> Update restricted params

- ads/aqua/common/utils.py
- ads/aqua/finetuning/finetuning.py
- ads/aqua/model/model.py
- docs/source/release_notes.rst
- pyproject.toml
This PR has code changes for the following:
- Update version and release notes.
- Integration test bug fix: 
- Remove validation for byom FT model deployment and fine-tuning.
- Update metadata to replace artifact location if already present.
- Pop base custom model flag from FT model to ensure it is not listed when model_type is set as BASE.
> Update version to 2.11.11 with bug fixes

- ads/config.py
Fixes getting default value for the threaded timeout. 
Without this fix the env variable will return a string value which will throw an error.
> Fixes getting default value for the threaded timeout.

- .github/workflows/run-unittests-py38-cov-report.yml
With recent PR from user, who is not in special write-permission-group, there was an error in one step of our test pipeline observed. That step showed 403 erorr (https://github.com/oracle/accelerated-data-science/actions/runs/9504255692/job/26199643545?pr=869) on sending POST to add comment into respective PR. Even though GH action has permissions set to write for pull-request, user should be able to have permission to write to repo (be in that special group).
To overcome this and future issues with PR from such users I am suggesting to make a step, which adds comment to PR optional (add continue-on-error: true). We still will have our coverage reports generated and published to artifacts and PR reviewers can see coverage downloading from artifacts generated by GH actions, but this will …
> Added "continue-on-error: true" to step which posts coverage comment

- ads/llm/langchain/plugins/base.py
- pyproject.toml
- tests/unitary/with_extras/langchain/test_serialization.py
We would like to relax langchain-core version restriction:
* 0.1.51 improve the serialization by saving model parameters. ( <= 0.1.50, the serialized object will not contain model parameters)
For gen ai plugin, we are going to put deprecation warning and point user to their own support in langchain.
> ODSC-58449: ads LangChain plugin update

- docs/source/release_notes.rst
- pyproject.toml
The latest update will cover changes related to:
- Update langchain dependencies.
- Support adding and removing artifact in a multi-model setting for model created by reference.
> Release v2.11.13

- ads/common/oci_logging.py
- Fixed the tail logging sort order to `DESC`
> Fixed tail logging

- .pre-commit-config.yaml
- pyproject.toml
- test-requirements.txt
Ruff can be used to replace Flake8 (plus dozens of plugins), Black, isort, pydocstyle, and more, all while executing tens or hundreds of times faster than any individual tool.
Added ruff to run mainly default settings with little extra and exclude. While developing our code we will add/exclude more. Please check on rules and suggest what can be added to default (section 'select' in pyproject.toml) and what can be excluded (section 'ignore' in pyproject.toml)- https://docs.astral.sh/ruff/rules/.
- added repo to .pre-commit-config.yaml
- added rules to pyproject.toml
- removed black, because ruff has drop-in parity with it
> Added ruff for pre-commit check

- ads/opctl/operator/common/operator_config.py
- ads/opctl/operator/lowcode/anomaly/schema.yaml
- ads/opctl/operator/lowcode/common/utils.py
- ads/opctl/operator/lowcode/forecast/schema.yaml
- tests/operators/common/test_load_data.py
When vault_secret_id is mentioned in input data schema, operators will fetch the database credentials from Vault.
> Vault support for Forecast & AD operators

- ads/aqua/extension/common_ws_msg_handler.py
- ads/aqua/extension/deployment_handler.py
- ads/aqua/extension/deployment_ws_msg_handler.py
- ads/aqua/extension/evaluation_ws_msg_handler.py
- ads/aqua/extension/models_ws_msg_handler.py
- ads/aqua/modeldeployment/deployment.py
- tests/unitary/with_extras/aqua/test_data/deployment/aqua_create_gguf_deployment.yaml
- tests/unitary/with_extras/aqua/test_data/deployment/deployment_config.json
- tests/unitary/with_extras/aqua/test_data/ui/container_index.json
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
- Support deployment of gguf models with cpu shapes 
- Add copyright/license text to missing python files
- Fix function typing to web socket handlers to work with python 3.8
- Ruff updates
```
python -m pytest -q tests/unitary/with_extras/aqua/test_deployment*
============================================= test session starts =============================================
collected 30 items
tests/unitary/with_extras/aqua/test_deployment.py .....................                                 [ 70%]
tests/unitary/with_extras/aqua/test_deployment_handler.py …
```
> [ODSC-59697] Llama cpp deployment support 

- ads/aqua/common/entities.py
- ads/aqua/common/enums.py
- ads/aqua/common/utils.py
- ads/aqua/constants.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/entities.py
- ads/aqua/ui.py
- tests/unitary/with_extras/aqua/test_data/ui/container_index.json
- tests/unitary/with_extras/aqua/test_decorator.py
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_ui.py
This PR covers the following changes:
- Add AquaContainerConfigSpec dataclass and return this information with the list_containers api.
- Disallow param override for llama cpp depoyment.
```
> python -m pytest -q tests/unitary/with_extras/aqua/test_*
=========================================================== test session starts ===========================================================
collected 195 items
tests/unitary/with_extras/aqua/test_cli.py ..............                                                                           [  7%] …
```
> [ODSC-60107] Return container spec with list containers API

- ads/aqua/common/utils.py
- ads/aqua/model/entities.py
- ads/aqua/model/model.py
- Added `download_from_hf: Optional[bool] = True` and `local_dir: Optional[str] = None` to `ImportModelDetails`
- Added logic to download and validate model from hugginface
- SAFETENSORS
- GGUF
> Added Logic to Download Model from HugginFace

- ads/aqua/common/enums.py
- ads/aqua/common/utils.py
- ads/aqua/extension/deployment_handler.py
- ads/aqua/extension/model_handler.py
- ads/aqua/model/entities.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
This PR covers the following changes:
- Register api takes in a parameter download_from_hf, set to True by default. For API call via model_handler, this is set as False. For CLI command, this will be set to true by default. The changes for HF flow will be covered in a different PR.
- AquaModelSummary has a field name change, model_format to model_formats.
- Validation changes when registering model via object storage.
```
POST http://localhost:8888/aqua/model
{
"model": "google/gemma-2b-it",
"os_path": "oci://<bucket>@<namespace>/<prefix>",
"inference_container": "odsc-tgi-serving"
}
```
```
{
"compartment_id": "ocid1.compartment.oc1..<ocid>",
"icon": "",
"id": "ocid1.datasciencemodel.oc1.iad.<ocid>",
"is_fine_tuned_model": false,
"license": "gemma",
"name": "google/gemma-2b-it", …
```
> [ODSC-60499] Update validation for models registered from object storage

- ads/aqua/app.py
- ads/aqua/common/utils.py
- ads/aqua/extension/model_handler.py
- ads/aqua/model/entities.py
- ads/aqua/model/model.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
- tests/unitary/with_extras/aqua/test_model.py
- tests/unitary/with_extras/aqua/test_model_handler.py
This PR adds the following:
- build_cli in app.py is updated to allow fields with value "False"
- added a new util function `get_hf_model_info` that caches the model info from Hugging Face for 5 hours. Cache size is set as 1.
- if model is downloaded from HF, tags for org and task are added.
- Unit tests for HF modules have been added
```
> python -m pytest -q tests/unitary/with_extras/aqua/test_*
================================================ test session starts =================================================
collected 208 items
tests/unitary/with_extras/aqua/test_cli.py …
```
> [ODSC-60499] Add HF tags for model and add additional tests

- .gitignore
- ads/aqua/evaluation/entities.py
- ads/aqua/evaluation/evaluation.py
In the initial implementation of the aqua-evaluate project, default model parameters were hard coded within the project. Given the diversity of LLM frameworks, which may support varying parameters under the Open AI spec, this setup could lead to compatibility issues. To enhance flexibility and adaptability, it is proposed to implement a pass-through mechanism. This mechanism would allow parameters from the client side to be directly forwarded to the LLM inferencing framework, enabling the framework to handle the parameters and generate errors. 
As a temporary solution, this PR addressing a list of mandatory service parameters that will be added on top of user-provided parameters during evaluation. 
```
model: Optional[str] = "odsc-llm"
add_generation_prompt: Optional[bool] = False
```
In …
> Adds service model parameters for the evaluation.

- ads/aqua/evaluation/evaluation.py
- tests/unitary/with_extras/aqua/test_evaluation.py
- tests/unitary/with_extras/aqua/utils.py
Shift the management of the supported metrics list from being hardcoded in the ADS SDK to being stored and managed at the evaluation service config level.
> [AQUA][Evaluate] Externalize Supported Evaluation Metrics List to Service Config

- ads/aqua/config/config.py
- ads/aqua/evaluation/evaluation.py
- tests/unitary/with_extras/aqua/test_config.py
- tests/unitary/with_extras/aqua/test_evaluation.py
> Fixes evaluation unit tests.

- ads/aqua/common/utils.py
- ads/aqua/extension/common_handler.py
- ads/aqua/extension/common_ws_msg_handler.py
- ads/aqua/extension/utils.py
- tests/unitary/with_extras/aqua/test_common_handler.py
- tests/unitary/with_extras/aqua/test_handlers.py
- add threaded decorator back to the load_config function.
- add ui_compatability_check function that caches the compartment info.
```
> python -m pytest -q tests/unitary/with_extras/aqua/test_*
===================================================== test session starts ======================================================
collected 230 items
tests/unitary/with_extras/aqua/test_cli.py ..............                                                                [  6%]
tests/unitary/with_extras/aqua/test_common_handler.py ... …
```
> Updated compatibility check for aqua

- ads/aqua/config/config.py
- ads/aqua/config/deployment_config_defaults.json
- ads/aqua/config/resource_limit_names.json
- docs/source/release_notes.rst
- pyproject.toml
This PR adds support for L40S shapes for AI Quick Actions. The next update will deprecate these defaults and move them to configs outside of ADS.
```
> python -m pytest -q tests/unitary/with_extras/aqua/*
============================================ test session starts ============================================
collected 244 items
tests/unitary/with_extras/aqua/test_cli.py ............................                               [  5%]
tests/unitary/with_extras/aqua/test_common_handler.py ...                                             [  6%] …
```
> ADS release with additional shapes support for AI Quick Actions

- ads/aqua/extension/finetune_handler.py
- ads/aqua/finetuning/entities.py
- ads/aqua/finetuning/finetuning.py
This PR intends to add changes in create FT api to pass early stopping params to SMC container if provided by user
> Passing Early stopping params to SMC container for finetuning

- ads/aqua/extension/deployment_handler.py
- ads/aqua/extension/errors.py
- ads/aqua/extension/model_handler.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
- tests/unitary/with_extras/aqua/test_model_handler.py
This PR intends to add delete/edit support for registered models along with delete/deactivate/activate support for model deployment
> Adding delete/activate/deactivate support for model deployment and registered models

- ads/aqua/modeldeployment/deployment.py
This PR is intended to add model specific task tag in Model deployment tags while creation of model deployment.
This will reduce number of api calls in client to get the model tags for Model deployment.
```
curl --location 'http://localhost:8888/aqua/deployments' \
--header 'Content-Type: application/json' \
--header 'Cookie: _xsrf=2|e9946301|bf91d5ae9f5db1d274d94b27e85a9e0c|1729063791; username-localhost-8888=2|1:0|10:1729063791|23:username-localhost-8888|196:eyJ1c2VybmFtZSI6ICIwYzE2NDliMGMxZjc0NmViYjdhMmFhNDAyZTVjMGFhOSIsICJuYW1lIjogIkFub255bW91cyBUYXlnZXRlIiwgImRpc3BsYXlfbmFtZSI6ICJBbm9ueW1vdXMgVGF5Z2V0ZSIsICJpbml0aWFscyI6ICJBVCIsICJjb2xvciI6IG51bGx9|620ae24da6b946a64d69e881d8934756fcbb805a109cb7b71561417cdb8bc20d' \
--data '{
"compartment_id": "ocid1.compartment.oc1...<ocid>", …
```
> Adding model task in MD tags

- ads/aqua/common/utils.py
This PR is intended to remove task parameter from HF list api to allow user to register unverified vision/embedding models
> Removing task parameter from list models HF api

- ads/aqua/extension/model_handler.py
- ads/aqua/model/model.py
This PR is intended to add delete model details cache method which will be helpful while editing default config for unverified models.  The cache needs to be deleted for the particular model for which update operation has been performed to get latest updated data in get call.
> Adding cache delete method for model details

- ads/aqua/evaluation/entities.py
- ads/aqua/evaluation/evaluation.py
- ads/aqua/extension/evaluation_handler.py
- tests/unitary/with_extras/aqua/test_evaluation.py
- tests/unitary/with_extras/aqua/test_evaluation_handler.py
- Made all entities in `evaluation` as `pydantic`
- Extended `AquaEvalParams` to accept all model parameters from customer
- Reverted [PR](https://github.com/oracle/accelerated-data-science/pull/942/files#diff-757a77f0e72a8116a357a68aa410c2259eba7252e817117a94e5ad1b031692baR178) to remove this logic to service container side.
- Create evaluation with model parameters
> Improve evaluation model params

- ads/secrets/adb.py
- tests/unitary/default_setup/secret/test_secretkeeper_adw.py
Adding support to input dsn in ADW secret to allow for TLS connections
> Add dsn attribute to ADWSecretKeeper

- ads/aqua/extension/deployment_handler.py
- ads/aqua/extension/model_handler.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
- tests/unitary/with_extras/aqua/test_model_handler.py
- Updated handlers for TEI deployment that will let users customize container URI and add custom cmd_vars during TEI deployment. 
- The previous update missed the handler changes that were used for registering from object storage.
- Updated unit tests
```
> python -m pytest -q tests/unitary/with_extras/aqua/*
======================================== test session starts ========================================
collected 249 items
tests/unitary/with_extras/aqua/test_cli.py ............................                       [  5%] …
```
> Allow customizing TEI deployment

- ads/dataset/dataset.py
- ads/dataset/factory.py
Bug Fix for issue #987 
`hide_index()` has been deprecated in pandas and has been replaced with `hide()`. This PR updates all occurrences of `hide_index` in ads.
> Replace hide_index to hide in ads

- ads/opctl/operator/lowcode/forecast/model_evaluator.py
- ads/opctl/operator/lowcode/forecast/utils.py
[ODSC-63260](https://jira.oci.oraclecorp.com/browse/ODSC-63260)
Improved auto-select robustness by selecting the best among successful models.
> Fix auto-select on model failure

- ads/aqua/evaluation/entities.py
- Disable protected_namespaces in Config to avoid printing a warning message for parameter starting with `model_`.
Before the fix:
```
> ads aqua model list
INFO:ads.common:Using 'api_key' authentication.
WARNING:py.warnings:/Users/user/miniconda3/envs/ads-aqua-v38/lib/python3.8/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_parameters" has conflict with protected namespace "model_".
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
warnings.warn(
{
"compartment_id": "ocid1.compartment.oc1..<ocid>",
"icon": "",
...
```
After the fix:
```
> ads aqua model list
INFO:ads.common:Using 'api_key' authentication.
{
"compartment_id": "ocid1.compartment.oc1..<ocid>",
"icon": "",
...
```
> Disable protected namespace warning

- ads/aqua/modeldeployment/deployment.py
When registering Aqua models via OSS flow, since user does not set the task, it is not available in the freeform tags. While deploying, this should be set to empty instead of None, else model deployment creation fails with "Invalid request tags" as shown below.
```
{
"status": 400,
"message": "Authorization Failed: Could not create resource. Operation Name: create_model_deployment.",
"service_payload": {
"target_service": "data_science",
"status": 400,
"code": "InvalidParameter",
"message": "Invalid request tags",
"operation_name": "create_model_deployment",
...
```
> Bug Fix for MD failure for deployment of Aqua models registered from OSS

- ads/aqua/app.py
- ads/aqua/evaluation/entities.py
- ads/aqua/evaluation/evaluation.py
- ads/aqua/extension/deployment_handler.py
- ads/aqua/extension/model_handler.py
- ads/aqua/finetuning/entities.py
- ads/aqua/finetuning/finetuning.py
- ads/aqua/model/entities.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/entities.py
- pyproject.toml
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
- tests/unitary/with_extras/aqua/test_evaluation.py
- tests/unitary/with_extras/aqua/test_finetuning.py
- tests/unitary/with_extras/aqua/test_model.py
- tests/unitary/with_extras/aqua/test_model_handler.py
This PR supports defined and freeform tags as inputs when creating resources in AI Quick Actions. The following have been updated:
- Creating model from verified models
- Registering new models (verified or unverified)
- Creating deployment
- Creating evaluation model, job and job run
- Creating finetuning model, job and job run
- Updated model and deployment handlers to accept freeform_tags and defined_tags, finetuning and evaluation accepts a json dict, so no updated needed.
- Unit tests to support all the changes
Following changes will be a part of subsequent PR:
- Improve deployment parameters (use dataclass)
- Update model and deployment handler to accept dict instead of individual params
Note:
hpo tests were failing since scikit-learn has updated `fit_params`  to `params` in …
> [ODSC-65517] Support freeform and defined tags for resource creation in Aqua

- .github/workflows/run-unittests-py39-py310.yml
- ads/llm/guardrails/base.py
- ads/llm/langchain/plugins/chat_models/oci_data_science.py
- ads/llm/langchain/plugins/llms/oci_data_science_model_deployment_endpoint.py
- pyproject.toml
- tests/unitary/with_extras/langchain/chat_models/test_oci_data_science.py
- tests/unitary/with_extras/langchain/llms/test_oci_model_deployment_endpoint.py
- The following classes will allow users to pass new parameters `headers`
-- ChatOCIModelDeployment
-- ChatOCIModelDeploymentVLLM
-- ChatOCIModelDeploymentTGI
-- BaseOCIModelDeployment
-- OCIModelDeploymentLLM
-- OCIModelDeploymentTGI
-- OCIModelDeploymentVLLM
Another PR will be made to `langchain_community` when this one is finalized
> Added headers parameters for ADS Langchain  

- ads/opctl/operator/lowcode/forecast/model/arima.py
- ads/opctl/operator/lowcode/forecast/model/automlx.py
- ads/opctl/operator/lowcode/forecast/model/autots.py
- ads/opctl/operator/lowcode/forecast/model/base_model.py
- ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
- ads/opctl/operator/lowcode/forecast/model/prophet.py
- ads/opctl/operator/lowcode/forecast/utils.py
- tests/operators/forecast/test_datasets.py
- tests/operators/forecast/test_errors.py
[ODSC-64830](https://jira.oci.oraclecorp.com/browse/ODSC-64830)
This PR maintain consistency in the input and output files across various components when performing single-series forecasts, particularly when the target_category_column parameter is not provided. The updates impact the following files:
- forecast.csv
- metrics.csv
- test_metrics.csv
- report.html
- local_explanation.csv
- global_explanation.csv
> Standardize outputs & report for single-series forecasts without target_category_columns

- .github/workflows/run-unittests-default_setup.yml
conda install fails for python 3.8 because of an issue related to version mismatch of conda-anaconda-telemetry package. This PR just disables the telemetry package install when python is set up. Anaconda has also announced end of support for python 3.8, we should eventually wind down 3.8 support in ads as well.
```
+ conda install python=3.8
Channels:
- defaults
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed
LibMambaUnsatisfiableError: Encountered problems while solving:
- package conda-anaconda-telemetry-0.1.1-py[39](https://github.com/oracle/accelerated-data-science/actions/runs/12676202695/job/35328893851#step:5:40)h06a4308_0 requires python >=3.9,<3.10.0a0, but none of the providers can be installed
Could …
```
> Skip python 3.8 tests

- ads/aqua/__init__.py
When accessing logger.handlers[0], it throws an IndexError since the handlers list is empty.
> Fix loglevel pr

- ads/llm/langchain/plugins/chat_models/oci_data_science.py
The `ChatOCIModelDeploymentVLLM` class contains inference parameters for vLLM APIs. However, updates on vLLM may remove some parameters, causing breaking change even if users do not use those parameters.
For example, the `early_stopping` parameter exist for [v0.6.2](https://docs.vllm.ai/en/v0.6.2/dev/sampling_params.html) but it is removed since [v0.6.3](https://docs.vllm.ai/en/v0.6.3/dev/sampling_params.html).
In the `ChatOCIModelDeploymentVLLM` class there is already [logic](https://github.com/oracle/accelerated-data-science/blob/ac40648536dcbeff4ca304fa83925c62219af2fc/ads/llm/langchain/plugins/chat_models/oci_data_science.py#L1005) to include parameters in the API request only if they are not `None`. However, since some of the parameters has a default value instead of `None`, they are …
> Set defaults for optional parameters in ChatOCIModelDeploymentVLLM

- ads/aqua/common/utils.py
- ads/aqua/data.py
- ads/aqua/extension/finetune_handler.py
- ads/aqua/finetuning/constants.py
- ads/aqua/finetuning/entities.py
- ads/aqua/finetuning/finetuning.py
- tests/unitary/with_extras/aqua/test_data/finetuning/ft_config.json
- tests/unitary/with_extras/aqua/test_finetuning.py
- tests/unitary/with_extras/aqua/test_finetuning_handler.py
This PR allows additional parameters to be passed as inputs for fine-tuning via Aqua. 
The changes also include converting all the finetuning entities dataclasses to pydantic. For restricting parameters, we use pydantic's validator to check if any of the inputs come from a restricted set of params, but also allow to skip validation in cases we load parameters from config files.
Also, the handler is updated since input validation is now done at the create() API level. Pydantic error message adds CL/RF characters, and unless wrapped around with custom validation, throws an "Illegal character" error when calling finish() at the handler level.
**1. When required param is not passed**
`Request: POST http://localhost:8888/aqua/finetuning`
```
Request payload without replica field
```
`Response` …
> [ODSC-63971] Allow additional parameters for finetuning

- ads/aqua/app.py
- ads/aqua/model/model.py
- tests/unitary/with_extras/aqua/test_config.py
- tests/unitary/with_extras/aqua/test_model.py
Currently we copy deployment_config.json and finetuning_config.json from service tenancy bucket into user bucket while registering the model. This causes inconsistency in future when new shape support is added or when we enable fine-tuning to verified models. User in this case is forced to delete and re-register the model so that the configurations get refreshed.
This PR ensures that :
- for verified models, we always refer to the service tenancy configuration so that when there is a new update, the existing registered models will pick it up. Because of this, we don't need to copy the config files in the user bucket anymore.
- for unverified models, user can create a config folder themselves and add it in artifact location. This will be a backdoor option if user wishes to customize their …
> [ODSC-66853] Load base model config by default

- docs/source/release_notes.rst
- pyproject.toml
Release ADS v2.12.10
PRs to merge prior to this:
- https://github.com/oracle/accelerated-data-science/pull/1053
- https://github.com/oracle/accelerated-data-science/pull/1047
> ADS release v2.12.10

- ads/aqua/app.py
- docs/source/release_notes.rst
- pyproject.toml
The PR https://github.com/oracle/accelerated-data-science/pull/1053 introduced a bug in the code that loads configuration files for finetuning and deployment. The issue was that the structure of the models without service tag is inconsistent, and the code didn't account for this. The fix for this is to check the parent directory of the artifact folder first (in case of verified models), and then check the artifact directory (for unverified models). 
The following applies to both `ft_config.json` and `deployment_config.json`.
1. Config for cached verified models
* model will not have "aqua_service_model" tag, hence artifact path will be set to the service bucket location.
* Example: `oci://service-managed-models@<namespace>/service_models/Mistral-7B-Instruct-v0.1/3dc28cf/config/ft_config.js …
> Fix config load paths and update ads version

- ads/aqua/common/entities.py
- ads/aqua/extension/deployment_handler.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/entities.py
- ads/aqua/modeldeployment/inference.py
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
- Move aqua create deployment function inputs from function to pydantic model.
- Update aqua model deployment entities to pydantic models.
- Introduce `model_info` field for creating multi-model deployment.
- Update unit tests
https://jira.oci.oraclecorp.com/browse/ODSC-56699
The new `model_info` field can be used for multi-model deployment. The PR only adds the field, the implementation in the create method is needed in order for this to work. The current `model_id` field can still be used for single model deployment.
```
POST /aqua/deployments/
{
"model_info": [
{"model_id": "test_model_ocid_1", "gpu_count": 2},
{"model_id": "test_model_ocid_2", "gpu_count": 2}
],
"instance_shape": "VM.GPU.A10.4",
"display_name": "model name",
}
```
```
POST …
```
> [ODSC-56699] Update MD entities to pydantic models

- ads/aqua/app.py
This PR intends to fix a bug in the API that fetches configuration for 
1. Fine-tuning
2. Deployment
3. Model tokenizer
```
Request:
http://localhost:8888/aqua/finetuning/config/ocid1.datasciencemodel.oc1.iad.xxxx
Response: 
{
"shape": {
"VM.GPU.A10.1": {
"batch_size": 1,
"replica": 1
}
},
"configuration": {
"micro_batch_size": 1,
"gradient_accumulation_steps": 1,
"gradient_checkpointing": true,
"val_set_size": 0.1,
"sequence_len": 2048,
"sample_packing": true,
"pad_to_sequence_len": true,
"optimizer": "adamw_torch",
"lr_scheduler": "cosine",
"learning_rate": 0.0002,
"flash_attention": true,
"bf16": true,
"fp16": false,
"tf32": false,
"logging_steps": 1,
"adapter": "lora",
"lora_r": 32,
"lora_alpha": 16,
"lora_dropout": 0.05,
"lora_target_linear": true,
"lora_target_modules": [
"q_proj", …
```
> [Bugfix][Urgent]  AQUA get configuration bugfix

- ads/aqua/extension/deployment_handler.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/utils.py
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
https://jira.oci.oraclecorp.com/browse/ODSC-68526
The `get_multimodel_compatible_shapes` method currently calls get_config sequentially for each model in the model_ids list, leading to inefficiencies and slow execution when handling multiple models.
This update refactors the method to leverage ThreadPoolExecutor for parallel execution, reducing latency and improving response times when retrieving deployment configurations for multiple models.
Additionally, all logic responsible for loading and processing the model deployment configuration has been moved into a separate class, **`MultiModelDeploymentConfigLoader`**. This improves code isolation, making it easier to maintain and test in the future.
> Optimize Multi-Model Configuration Retrieval Using Parallel Execution

- ads/aqua/extension/deployment_handler.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/entities.py
- ads/aqua/modeldeployment/utils.py
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
- Modified get deployment config as pydantic class `AquaDeploymentConfig` and made all fields as optional.
- Added checker for `get_multimodel_deployment_config` to handle deployment config when some fields are empty.
- Fixed unit tests
> Modify get deployment config as pydantic

- ads/model/model_metadata.py
- tests/unitary/default_setup/model/test_datascience_model.py
- tests/unitary/default_setup/model/test_model_artifact.py
- tests/unitary/default_setup/model/test_model_metadata.py
This PR updates the **model-defined metadata implementation** to accept **non-predefined keys**.  
In the original implementation, the **defined metadata keys** were **hardcoded**, meaning only a predefined set of keys were accepted. However, the **Model Catalog (MC) service** plans to introduce additional metadata keys, which could cause compatibility issues for **ADS**.  
Currently, if users attempt to **load a model from the Model Catalog** using:  
```python
DataScienceModel.from_id("<OCID>")
```  
they will encounter an **error** if unexpected metadata keys are present.  
This PR **removes the restriction** on predefined metadata keys, allowing **non-predefined keys** to be accepted without causing failures.  
```python
class MetadataTaxonomyKeys(ExtendedEnum):
USE_CASE_TYPE = …
```
> Enhancing Model-Defined Metadata Handling

- ads/model/artifact_downloader.py
- ads/model/datascience_model.py
- ads/model/service/oci_datascience_model.py
- tests/unitary/default_setup/model/test_artifact_downloader.py
- tests/unitary/default_setup/model/test_datascience_model.py
- tests/unitary/default_setup/model/test_oci_datascience_model.py
This PR resolves a recursion issue that occurred when creating a new model in Model Catalog (MC) with the new OCI SDK version.
The new **oci.data_science.models.Model** introduced an **is_model_by_reference** field, which conflicts with the existing **is_model_by_reference** property in [OCIDatascienceModel](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/service/oci_datascience_model.py#L92).
Since **OCIDatascienceModel** inherits from **oci.data_science.models.Model**, having the same attribute name caused recursive calls when serializing the model using **sanitize_for_serialization** from the OCI SDK.
This led to failures when attempting to create a new model in MC.
Renamed  **is_model_by_reference** to **_is_model_by_reference** in **OCIDatascienceModel** to …
> Fix Recursion Issue in OCIDatascienceModel Due to is_model_by_reference Conflict in New OCI SDK

- docs/source/user_guide/large_language_model/aqua_client.rst
- docs/source/user_guide/large_language_model/index.rst
- docs/source/user_guide/large_language_model/training_llm.rst
This pull request enhances the existing LLM documentation and adds the AI Quick Actions Client documentation.
> Add AQUA HTTP Client Documentation

- ads/aqua/evaluation/evaluation.py
- tests/unitary/with_extras/aqua/test_evaluation.py
The "name" parameter in the model parameters had to be updated from using the same default name for all deployments to the model's specific name.  
This PR introduces a method to validate the user's input when they specify the model name for targeting a single model for evaluation when the model is within a multi model deployment. 
Added method validate_name_multi_model():
- used in AquaEvaluationApp.create() in evaluation.py.
- assumes that the UI and evaluation handler sends back the user's input model parameters, which includes the "name" parameter with the key being the model specific name
- we check the DataScienceModel metadata for the model specific name (configuration setting) and whether this name matches the user's input.
Wrote test cases in test_deployment() in the …
> ODSC 68580- Update Evaluation SDK to Support Multi-Model Deployment

- ads/common/utils.py
- ads/model/datascience_model.py
- tests/unitary/default_setup/common/test_common_utils.py
This PR replaces the deprecated (in python 3.11) ```cgi.parse_header``` usage with a custom, pure-Python implementation for parsing Content-Disposition headers. 
```
artifact_info = {"Content-Disposition": 'attachment; filename="example.txt"'}
_, file_name_info = parse_content_disposition(artifact_info["Content-Disposition"])
print("Parameters:", file_name_info)
artifact_info = {"Content-Disposition": "attachment; filename=example.txt"}
_, file_name_info = parse_content_disposition(artifact_info["Content-Disposition"])
print("Parameters:", file_name_info)
artifact_info = {"Content-Disposition": '  attachment ;  filename =   "example.txt" ; param = value  '}
disposition, file_name_info = parse_content_disposition(artifact_info["Content-Disposition"])
print("Parameters:", file_name_info) …
```
> Implement Custom Content-Disposition Header Parser to get rid of the CGI dependency

- ads/opctl/operator/lowcode/forecast/model/automlx.py
- ads/opctl/operator/lowcode/forecast/model/base_model.py
Explanation fixes for errors and explanation csv's, also adds the missing abs in the amlx explainer.
> Explanation fixes for error and output generation.

- ads/aqua/common/constants.py
- ads/aqua/common/entities.py
- ads/aqua/common/enums.py
- ads/aqua/common/utils.py
- ads/aqua/extension/base_handler.py
- ads/aqua/extension/deployment_handler.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/entities.py
- ads/aqua/modeldeployment/utils.py
- tests/unitary/with_extras/aqua/test_common_entities.py
- tests/unitary/with_extras/aqua/test_data/deployment/aqua_deployment_shapes.json
- tests/unitary/with_extras/aqua/test_deployment.py
This PR updates the multi-model deployment logic to fetch the total available GPU count directly from the `list_model_deployment_shapes` API, instead of relying on static multi-model configurations. This change ensures that GPU allocation aligns with the latest shape specifications provided by the Model Deployment service.
- Integrated `list_model_deployment_shapes` API to dynamically retrieve available GPU count per shape.
- Updated multi-model deployment logic to use real-time API data instead of relying on predefined configurations.
- Modified shape-related calculations to ensure accurate GPU allocation.
- Added unit tests to validate GPU count retrieval from the API.
- Added a dedicated **handler** for **Model Deployment** to retrieve the list of **available shapes**.
- Temporary …
> Extract Available GPU Count from list_model_deployment_shapes API for Multi-Model Deployment

- ads/model/artifact_downloader.py
- ads/model/datascience_model.py
- ads/model/service/oci_datascience_model.py
- tests/unitary/default_setup/model/test_artifact_downloader.py
- tests/unitary/default_setup/model/test_datascience_model.py
- tests/unitary/default_setup/model/test_oci_datascience_model.py
This PR intends to solve the conflict issue with OCIDatascienceModel class due to a conflicting field name 
`_ is_model_by_reference` with latest preview sdk
https://github.com/oracle/accelerated-data-science/pull/1073
The test case `test_is_model_by_reference` was failing with latest preview sdk
In the OCI SDK, attributes are always defined with both attr and _attr. Both is_model_by_reference and _ is_model_by_reference are defined in the new SDK.  Hence , to avoid conflict , renaming `_is_model_by_reference` to `is_model_created_by_reference` in ADS.
The screenshot of the conflicting attribute in latest oci sdk:
> Fixing conflict in OCIDatascienceModel Due to is_model_by_reference with latest preview sdk

- ads/aqua/config/container_config.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
This update modifies the **multi-model deployment validation** by replacing the **static container family check** with a **usage-based approach**. Instead of relying on a hardcoded container family, the validation now leverages the **`usages`** attribute, which includes a **`multi_model`** tag for containers that support multi-model deployment.
> Switch Multi-Model deployment container validation to usage-based tagging

- ads/aqua/app.py
- ads/aqua/common/entities.py
- ads/aqua/finetuning/finetuning.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
- tests/unitary/with_extras/aqua/test_config.py
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_finetuning.py
This PR refactors the AQUA `get_config` method.
- Previously, the method retrieved the config based on model_ocid by first fetching details from the Model Catalog, extracting the config location, and then loading and returning the config in dictionary format.
- With this update, the method now returns both the model details and the config in a Pydantic format.
The model retrieved from **Model Catalog** will be reused across multiple places, reducing the need to repeatedly request model details.
> [AQUA] Enhance get_config to Return Model Details and Configuration in a Pydantic format

- ads/aqua/common/entities.py
- ads/aqua/constants.py
- ads/aqua/evaluation/evaluation.py
- ads/aqua/model/constants.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
- tests/unitary/with_extras/aqua/test_data/deployment/aqua_multi_model.yaml
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_evaluation.py
- tests/unitary/with_extras/aqua/test_model.py
- Applied `create_custom_metadata_artifact` to store multi model metadata in model catalog while creating the aqua model.
- Applied `get_custom_metadata_artifact` to get multi model metadata in model catalog while fetching the aqua deployment.
> Changed multi model metadata storage.

- ads/llm/__init__.py
- ads/llm/langchain/plugins/llms/oci_data_science_model_deployment_endpoint.py
This update **relaxes** the `OCIModelDeploymentLLM` by **decoupling** the default model parameters. This change allows `OCIModelDeploymentLLM` to be used with **various frameworks**, rather than being restricted to **VLLM** and **TGI**.
> Relaxes OCIModelDeploymentLLM 

- docs/source/release_notes.rst
- pyproject.toml
* Upgraded OCI SDK to ``v2.148.0`` for improved compatibility and performance.
* Added support to launch the **AI Quick Actions API server** from anywhere using:
```
python -m ads.aqua.server
```
* Introduced ``HttpxOCIAuth`` class, enabling HTTPX clients to sign requests using **OCI signers**, ensuring compatibility with **OCI Model Deployment services and LLM models**.
* **Forecast Operator:**
* Optimized the **auto-select** feature to prevent redundant data re-saving during cross-validation.
* Implemented **AutoMLx Global Explainer** for enhanced model interpretability.
* **Bug Fixes:**
* Fixed the Python 3.11 Compatibility. Replaced the deprecated ``cgi.parse_header`` function with a custom **pure-Python implementation** for parsing ``Content-Disposition`` headers.
* Resolved a …
> Bumps the ADS version to 2.13.1

- ads/model/model_metadata.py
Disable new taxonomy metadata tags in  `model_metadata.py`  to make them optional.
> Disable new taxonomy metadata tags in  model_metadata.py

- ads/aqua/evaluation/evaluation.py
- ads/aqua/finetuning/finetuning.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
Since we migrated AQUA to use Pydantic objects, the fire package used for automatically parsing the method docstring now does not disclose the parameters for Pydantic objects used in several AQUA methods. The CLI --help command needed to be updated to give the user more insight on the parameters of these Pydantic objects.
For the following CLI AQUA commands, added Github Links to relevant documentation about flags. 'kwargs' were also added to the method docstring as well.
`ads aqua model register --help`
`ads aqua deployment create --help`
Comment- I know this one looks crazy- Any suggestions? I followed the example [here ](https://github.com/oracle/accelerated-data-science/blob/feature/multi_model_deployment/ads/aqua/model/model.py#L1653)for formatting, but fire package is rendering the …
> Additional CLI Support for AQUA with Pydantic Objects

- ads/aqua/modeldeployment/deployment.py
Added error to fix bug encountered on-call. 
BUG:
if a user is in a region (ie. Singapore West) where the following shapes (VM.GPU.A10.1, VM.GPU.A10.2, etc) are not available, the error thrown is non-descriptive and shows as an auth error.
We now throw an Invalid Instance Name error complete with details about the unavailable shape. 
Ideally, the shape should not even be listed in the AQUA UI if not available in the region.
> Added Error Message for Unavailable Shape in Region

- ads/aqua/evaluation/evaluation.py
Similar to #1122, the workflow for creating an AQUA evaluation also needs to be updated to avoid permission issue.
Defined tags will be added when creating the model instead of updating the model, so that tags added by the tenancy automatically will not be updated.
> Add defined_tag when creating the model instead of updating the model.

- ads/common/utils.py
- ads/model/datascience_model.py
- ads/model/service/oci_datascience_model.py
This PR is intended to improve API for creating and updating metadata artifact which was introduced as part of MS enhancements.
While uploading metadata artifact , the type of content should always be bytes.  Earlier it was both bytes and strings.
When uploading the content via local path
```
from ads.model.common.utils import MetadataArtifactPathType
from ads.model.datascience_model import DataScienceModel
ds_model=DataScienceModel.from_id("ocid1.datasciencemodel.oc1.iad.xxyz")
ds_model.create_defined_metadata_artifact(
"README",
artifact_path_or_content="/Users/<username>/Downloads/README.md",
path_type=MetadataArtifactPathType.LOCAL
)
```
When uploading the content via OSS path
```
from ads.model.common.utils import MetadataArtifactPathType
from ads.model.datascience_model import …
```
> [DRCC] Create and Update Metadata artifact content changes

- ads/aqua/config/container_config.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
- tests/unitary/with_extras/aqua/test_data/ui/container_index.json
- tests/unitary/with_extras/aqua/test_ui.py
This PR is intended to update the `Usage` enum for multi model deployment to unblock DRCC feature adoption.
https://bitbucket.oci.oraclecorp.com/projects/ODSC/repos/odsc_artifact_deployer/pull-requests/260/overview
> [Multi model deployment] Updating usages for container config

- ads/aqua/constants.py
- ads/aqua/extension/aqua_ws_msg_handler.py
- ads/aqua/extension/base_handler.py
- ads/aqua/extension/errors.py
- ads/aqua/extension/utils.py
- docs/source/user_guide/aqua/apiserver.rst
- tests/unitary/with_extras/aqua/test_decorator.py
- tests/unitary/with_extras/aqua/test_handlers.py
- tests/unitary/with_extras/aqua/test_model_handler.py
Currently, the AQUA UI throws generic errors when auth issues arise- not informing the user of potential solutions and suggested policy additions to fix the error.
Added 'troubleshooting_tips' section (see example json below)
- links to the specific section (as specified by the operation error from the OCI Service Error) to our AQUA troubleshooting page 
**result** : user will obtain a specific action to fix their auth issue 
Distinguish between Auth error versus tag related error.
- certain operations have two methods for failure- auth related and tag related. We use the OCI Service Error to single out 'Invalid tag' errors for the create_model and update_model operations
**result**: user obtains a different fix for a tag-related error vs. an auth error
Refactored write_error in used in …
> Corrected: Improved AQUA Error Messages for Authorization and Tag-Related Uses 

- ads/aqua/common/enums.py
- ads/aqua/common/utils.py
- ads/aqua/model/model.py
- tests/unitary/with_extras/aqua/test_common_utils.py
This PR introduces support for relaxing container family validation in multi-model deployment by incorporating container family compatibility rules.
- Introduced `CONTAINER_FAMILY_COMPATIBILITY` map, which defines compatible container families and preferred family when multiple compatible types are detected.
- Example: `"odsc-vllm-serving"` and `"odsc-vllm-serving-v1"` are now treated as compatible; `"odsc-vllm-serving-v1"` is preferred.
- Updated model validation logic to:
- Detect when all models belong to compatible families.
- Automatically select the preferred container family for deployment.
- Raise errors when incompatible or missing families are found.
- Utility function: `get_preferred_compatible_family(...)`
- Returns the best-suited family from a list based on the compatibility …
> Enhance the container family validation for multi-model deployment

- ads/aqua/__init__.py
- ads/aqua/cli.py
- ads/aqua/common/utils.py
- ads/aqua/config/container_config.py
- ads/aqua/extension/common_ws_msg_handler.py
- ads/aqua/extension/model_handler.py
- ads/aqua/extension/utils.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
- ads/config.py
- tests/unitary/with_extras/aqua/test_cli.py
- tests/unitary/with_extras/aqua/test_common_handler.py
- tests/unitary/with_extras/aqua/test_model.py
- tests/unitary/with_extras/aqua/test_model_handler.py
- tests/unitary/with_extras/aqua/test_ui.py
This PR is intended to completely remove the dependency of AQUA on config stored in Object storage bucket.  Also , this change would ensure Aqua will be available for all realms even when no `ODSC_MODEL_COMPARTMENT_OCID` env variable is set.
> [DRCC][AQUA] Completely Removing OSS bucket config dependency

- ads/opctl/operator/lowcode/forecast/model/automlx.py
[ODSC-71305](https://jira.oci.oraclecorp.com/browse/ODSC-71305)
> Updated train metrics generation for AutoMLX model

- ads/aqua/finetuning/finetuning.py
- ads/aqua/model/model.py
For fine-tuned model , we need to update defined metadata to include Deployment Configuration , Readme , and License so that the call to fetch these config doesn't go to service tenancy bucket (for cached model).
> Adding defined metadata to fine-tuned model

- ads/aqua/constants.py
- ads/aqua/model/entities.py
- ads/aqua/model/model.py
- tests/unitary/with_extras/aqua/test_model.py
- Adopt model file description while creating multi model, instead of calling `add_artifact` as this may cause authentication error to object storage.
```
tests/unitary/with_extras/aqua/test_model.py::TestAquaModel::test_create_model PASSED   [  2%]
tests/unitary/with_extras/aqua/test_model.py::TestAquaModel::test_create_multimodel PASSED [  5%]
tests/unitary/with_extras/aqua/test_model.py::TestAquaModel::test_get_foundation_models[service] PASSED [  8%]
tests/unitary/with_extras/aqua/test_model.py::TestAquaModel::test_get_foundation_models[verified] PASSED [ 11%]
tests/unitary/with_extras/aqua/test_model.py::TestAquaModel::test_get_model_fine_tuned PASSED [ 14%]
tests/unitary/with_extras/aqua/test_model.py::TestAquaModel::test_import_verified_model[True-True-True] PASSED [ 17%] …
```
> Adopt model file descriptions while creating multi model

- ads/aqua/common/utils.py
This PR enhances the `load_gpu_shapes_index` function to merge GPU-shape definitions from two sources—an OCI Object Storage bucket and a local JSON file, so that any shapes defined remotely override their local counterparts, while still falling back cleanly if the remote load fails.
---
1. **Separate remote vs. local loads**
* We now load `remote_data` and `local_data` into two distinct dictionaries.
* If the `CONDA_BUCKET_NS` environment variable is set, we attempt to read from Object Storage.
2. **Merge logic**
* After loading both sources, we merge the two on the `"shapes"`. Any entry present in `remote_data["shapes"]` **overrides** the same key in `local_data`, while preserving local entries not present remotely.
3. **Return the merged index**
> Merge local and remote GPU shapes index, preferring Object Storage overrides

- ads/aqua/common/utils.py
- tests/unitary/with_extras/aqua/test_utils.py
When a parameter has more than 1 values, the current parsing logic only takes in 1 value and ignores the remaining ones. These changes would fix this and accept all values.
```
params = "--gpu-memory-utilization 0.98 --max-loras 2 --lora-modules speech=1234 vision=2345 --dtype auto"
get_params_dict(params)
```
```
{'--gpu-memory-utilization': '0.98',
'--max-loras': '2',
'--lora-modules': 'speech=1234',
'--dtype': 'auto'}
```
```
{'--gpu-memory-utilization': '0.98',
'--max-loras': '2',
'--lora-modules': 'speech=1234 vision=2345',
'--dtype': 'auto'}
```
```
> python -m pytest -q tests/unitary/with_extras/aqua/test_utils.py
=============================================== test session starts ================================================
platform darwin -- Python 3.11.11, pytest-8.3.4, …
```
> Param parsing issue fix

- ads/aqua/app.py
- ads/aqua/modeldeployment/utils.py
This PR enhances the `_fetch_deployment_config_from_metadata_and_oss` function to support retrieving deployment configuration for fine-tuned models by falling back to their base model metadata when necessary.
* **Fine-Tuned Model Support:**
* If the model contains the `AQUA_FINE_TUNED_MODEL_TAG`, the function now attempts to resolve the base model ID from the `custom_metadata_list`.
* If the base model is found, its metadata or Object Storage entry will be used to retrieve the deployment configuration.
* **Fallback Handling:**
* If the base model ID is not found or the metadata key is missing, the function logs a clear message and continues with fallback logic.
* Still supports retrieving configuration from Object Storage if not found in metadata.
> [AQUA][MMD] Add Support for Retrieving Deployment Configuration from Base Model for Fine-Tuned Models

- ads/aqua/common/enums.py
- ads/aqua/model/model.py
- tests/unitary/with_extras/aqua/test_common_utils.py
Adds VLLM LLaMA 4 support to the list of compatible container families for Multi-Model deployment.
> Adds VLLM LLaMA 4 support to the list of compatible container families for Multi-Model deployment.

- ads/aqua/common/entities.py
- ads/aqua/common/utils.py
- ads/aqua/model/model.py
- ads/aqua/model/utils.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/group_model_metadata.py
- tests/unitary/with_extras/aqua/test_deployment.py
- tests/unitary/with_extras/aqua/test_deployment_handler.py
**TODO:**
- writing docstrings for methods in group_model_metadata
- unit tests (want to seek feedback on implementation before writing tests)
This PR migrates the construction of the 'MULTI_MODEL_CONFIG', an environment variable passed to start a multi-model deployment, from the _create_multi method in deployment.py to group_model_metadata.py. 
**In group_model_metadata.py**
- we convert CreateModelDeploymentDetails -> GroupModelDeploymentMetadata (pydantic object representing MULTI_MODEL_CONFIG)
- during ^^ conversion, we validate if duplicate model entries exist or if duplicate LoRA Modules exist per model.
When constructing CreateModelDeploymentDetails in model.py, we construct a new field ```fine_tune_weights``` with the following format:
```
"fine_tuned_weights": [
{
"model_path": …
```
> [AQUA][MMD] Enhance Multi-Model Deployment Configuration to Support FT Models

- ads/aqua/extension/deployment_handler.py
This PR is intended to update the inference logic when user overrides the header to /v1/chat/completions in case of model deployed with llama-cpp container.   MD with llama cpp container returns chunked response in different format than vllm/tgi containers.
> Updating chat completions inference data retrieval logic

- ads/aqua/cli.py
- docs/source/ads.rst
This feature enables easy installation of the Aqua extension from Jupyter Lab.
> CLI to install aqua extenstion in Jupyterlab

- ads/aqua/client/client.py
- ads/aqua/client/openai_client.py
- docs/source/user_guide/large_language_model/aqua_client.rst
- tests/unitary/with_extras/aqua/test_client.py
Update the AQUA documentation and the AQUA OpenAI client to support multiple inference endpoints in OCI Model Deployment.
> Update the AQUA documentation and the AQUA OpenAI client to support multiple inference endpoints in OCI Model Deployment.

- ads/aqua/extension/model_handler.py
- tests/unitary/with_extras/aqua/test_model_handler.py
This PR addresses an issue where large chat templates stored in the model's custom metadata were being returned as improperly encoded strings, resulting in frontend inference failures.
The returned response is now safely decoded to UTF-8 when it’s in bytes form, preserving chat template regardless of size.
---
- Updated the get() handler in AquaModelChatTemplateHandler to correctly decode byte strings returned by get_custom_metadata_artifact.
- Adjusted related unit tests to reflect updated error messages and behavior.
> Fix inference failure caused by improper handling of large chat templates

- ads/aqua/constants.py
- ads/aqua/model/model.py
- tests/unitary/with_extras/aqua/test_model.py
- Added `convert_fine_tune` to convert legacy fine tuned model to v2.
- Convert legacy fine tuned model to v2 via cli
- Fine tuned model v2 will have tag `fine_tune_model_version` and only fine tune artifacts in `model_file_description.json`
```
============================================= test session starts =============================================
platform darwin -- Python 3.13.2, pytest-8.3.5, pluggy-1.5.0 -- /Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13
plugins: anyio-4.9.0, langsmith-0.3.15, mock-3.14.0, xdist-3.6.1
collected 35 items …
```
> Added cli to convert legacy fine tuned model to v2.

- ads/aqua/common/utils.py
- ads/aqua/modeldeployment/config_loader.py
- ads/aqua/modeldeployment/deployment.py
- tests/unitary/with_extras/aqua/test_data/deployment/aqua_multi_model_deployment_config.json
- tests/unitary/with_extras/aqua/test_data/deployment/deployment_config.json
- tests/unitary/with_extras/aqua/test_data/deployment/deployment_gpu_config.json
- tests/unitary/with_extras/aqua/test_deployment.py
**Summary**
This PR updates the AQUA deployment config reader to support **shape-specific environment variables** for GPT-OSS model deployments. The change introduces an `env` section in the deployment configuration for A-series GPU shapes, allowing AQUA handlers to return custom environment variables alongside existing parameter sets.
**Example**
A request to:
```
/aqua/deployments/{model_ocid}/params?instance_shape=BM.GPU4.8
```
will now return:
```json
{
"data": [
"--trust-remote-code",
"--gpu-memory-utilization 0.98",
"--enforce-eager",
"--max-num-seqs 32",
"--max_model_len 130000",
"--dtype bfloat16"
],
"env": {
"VLLM_ATTENTION_BACKEND": "TRITON_ATTN_VLLM_V1"
}
}
```
This change is required to ensure GPT-OSS model deployments on A-series shapes use the correct VLLM attention backend …
> [AQUA][GPT-OSS] Add Shape-Specific Env Config for GPT-OSS Models in AQUA Deployment Config Reader

- ads/aqua/common/utils.py
- ads/aqua/constants.py
- ads/aqua/finetuning/finetuning.py
- ads/aqua/model/model.py
- ads/aqua/model/utils.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/entities.py
- ads/model/datascience_model_group.py
- tests/unitary/with_extras/aqua/test_deployment.py
- Block legacy ft model from stack/multi/single deployment
- create multi deployment with legacy AQUA model
- create stacked deployment with legacy AQUA model
- create single deployment with legacy AQUA model
```
============================================= test session starts =============================================
platform darwin -- Python 3.13.2, pytest-8.3.5, pluggy-1.5.0 -- /Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13
plugins: anyio-4.9.0, langsmith-0.3.15, mock-3.14.0, xdist-3.6.1
collected 88 items                                                                                            
tests/unitary/with_extras/aqua/test_deployment.py::TestAquaDe …
```
> [AQUA] Block legacy ft model

- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/entities.py
- tests/unitary/with_extras/aqua/test_deployment.py
- Block deploying legacy ft model as single model deployment.
- Block deploying ft model v2 as single model deployment.
> [AQUA] Block deploying ft model as single model deployment.

- ads/aqua/common/entities.py
- ads/aqua/resources/gpu_shapes_index.json
- tests/unitary/with_extras/aqua/test_data/recommend/result-Devstral-Small-2507-GQA.json
- tests/unitary/with_extras/aqua/test_data/recommend/result-Kimi-K2-Instruct-MOE.json
- tests/unitary/with_extras/aqua/test_data/recommend/result-Qwen3-235B-A22B-Instruct-2507-FP8.json
- tests/unitary/with_extras/aqua/test_recommend.py
This PR updates the GPU shapes index file to:
* Add new GPU shapes
* Include additional CPU parameters
Keeping the GPU shapes index up to date ensures accurate configuration and compatibility across deployments. Adding CPU parameters provides more complete resource specifications for better validation and deployment planning.
> Update GPU shapes index with additional shapes and CPU parameters

- ads/aqua/common/entities.py
- ads/aqua/common/utils.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/model_group_config.py
- tests/unitary/with_extras/aqua/test_common_entities.py
- tests/unitary/with_extras/aqua/test_deployment.py
This pull request introduces enhancements and refactoring aimed at improving the deployment configuration flow for both single-model and multi-model deployment scenarios.
1. **Support for Default Environment Variables in Single Model Deployment**
* Added logic to read default environment variables from the model config.
* Users can override these environment variables explicitly when needed.
2. **Code Refactoring for Configuration Parsing**
* Cleaned up and consolidated helper methods for parsing CLI-style parameters (`params`) and environment variables (`env_var`).
* Improved function docstrings and test coverage for better maintainability.
3. **Multi-Model Deployment Entity Enhancements**
* Extended the `AquaMultiModelRef` structure to support both `params` and `env_var` sections.
* …
> AQUA. Support env var overrides and enhance multi-model entity structure

- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/entities.py
- tests/unitary/with_extras/aqua/test_deployment.py
- If deploying single ft v2 model, switch to stack deployment
- If deploying single ft legacy model, stick to single deployment
```
===================================================== test session starts =====================================================
platform darwin -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0 -- /Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13
plugins: anyio-4.10.0
collected 88 items                                                                                                            
tests/unitary/with_extras/aqua/test_deployment.py::TestAquaDeployment::test_create_deployment_for_fine_tuned_model PASSED [  1%] …
```
> [AQUA][STMD]Updated logic to deploy single ft model

- ads/model/runtime/utils.py
- tests/unitary/with_extras/evaluator/test_evaluator.py
- tests/unitary/with_extras/model/test_generic_model.py
- tests/unitary/with_extras/model/test_model_metadata_mixin.py
Fixed a bug with extracting conda metadata during prepare artifacts.
> Fix for JIRA ODSC-77609. 

- ads/aqua/modeldeployment/deployment.py
- tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
- Fixed custom `model_name` only for single deployment.
- Fixed unit tests
```
================================================= test session starts =================================================
platform darwin -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0 -- /Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13
plugins: anyio-4.10.0
collected 90 items                                                                                                    
tests/unitary/with_extras/aqua/test_deployment.py::TestAquaDeployment::test_create_deployment_for_fine_tuned_model PASSED [  1%]
tests/unitary/with_extras/aqua/test_deployment.py::TestAquaDeployment::test_create_deployment …
```
> Fixed custom model name for single deployment.
