oracle/accelerated-data-science

- docs/requirements.txt
Fix for versioned documentation - readthedocs
> Readthedocs v2.5.9

- docs/source/index.rst
- docs/source/user_guide/model_version_set/associate_a_model.rst
- docs/source/user_guide/model_version_set/create.rst
- docs/source/user_guide/model_version_set/delete.rst
- docs/source/user_guide/model_version_set/download.rst
- docs/source/user_guide/model_version_set/index.rst
- docs/source/user_guide/model_version_set/list.rst
- docs/source/user_guide/model_version_set/overview.rst
- docs/source/user_guide/model_version_set/quick_start.rst
- docs/source/user_guide/model_version_set/update.rst
Add Model Version Set user guide.
> ODSC-36680: [MVS][User Guide] Add Model Version Set user guide.

- docs/source/user_guide/cli/opctl/localdev/condapack.rst
- docs/source/user_guide/model_registration/frameworks/lightgbmmodel.rst
- docs/source/user_guide/model_registration/frameworks/pytorchmodel.rst
- docs/source/user_guide/model_registration/frameworks/sklearnmodel.rst
- docs/source/user_guide/model_registration/frameworks/sparkpipelinemodel.rst
- docs/source/user_guide/model_registration/frameworks/tensorflowmodel.rst
- docs/source/user_guide/model_registration/frameworks/xgboostmodel.rst
- docs/source/user_guide/model_registration/model_deploy.rst
- docs/source/user_guide/model_registration/quick_start.rst
Update documentation with raw-request command examples to run model deployment predictioons.
- updated frameworks pages with raw-request examples: lightgbm, pytorch, sklearn, sparkmodel, tensorflow, xgboost
- updated quick start with train data provided into prepare() methods
- updated condapack cli commands section about NO_CONTAINER env var
> ODSC-36358. [ads_docs] Add raw-request examples for Deployment section

- .gitignore
- docs/README.md
Adjusts  documentation setup guide.
> Adjusts documentation setup guide.

- docs/source/release_notes.rst
Fixes release notes for 2.7.2.
> Fixes release notes.

- ads/jobs/ads_job.py
- docs/source/user_guide/jobs/data_science_job.rst
- docs/source/user_guide/jobs/run_notebook.rst
This PR aims to fix the bug in jobs, and update tensorflow pack used in example.
> Fixes jobs example

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- fixed formatting of yml template
- removed security link form config.yml, it already exists in GH
> Odsc 37075/bug report template

- docs/source/index.rst
- docs/source/user_guide/model_training/distributed_training/overview.rst
- docs/source/user_guide/model_training/index.rst
Dropping the Beta tag around the title for distributed training
> drop LA tag

- docs/source/user_guide/apachespark/dataflow.rst
Extends documentation with the demonstrating of usage environment variables and private endpoints within the Data Flow SDK.
> Improves Data Flow user guide with the new features.

- ads/database/connection.py
Update docstring per internal policy about password examples in documentation.
Details in comments in ODSC-39825 jira Ops task.
> Updated docstring per internal policy

- .github/ISSUE_TEMPLATE/feature_request.yml
Added template for feature request, which will appear in section "Issues" -> "New issue" in current github project.
Jira: ODSC-40893
- added file .github/ISSUE_TEMPLATE/feature_request.yml
> Add feature request template -> Main

- .github/ISSUE_TEMPLATE/feature_request.yml
Added template for feature request, which will appear in section "Issues" -> "New issue" in current github project.
Jira: ODSC-40893
- added file .github/ISSUE_TEMPLATE/feature_request.yml
> Add feature request template -> Develop

- ads/opctl/utils.py
It is better to `print` instead of `log` the container logs as they are expected outputs to the terminal.
Currently the container logs are handled by `logger.info()`. The default log level is warning. So user will not see anything unless the debug flag (-d) is used. Normally users would expect to see the container logs in the terminal. For example, when a user run `echo` command, the user would expect to see the string printed. But currently nothing is showed.
Also, striping each line of the output will also remove tabs and spaces at both ends. It is better to print the output as is and use empty string for the `end` argument.
For example, with `print(line.decode("utf-8").strip())`, the `cat --help` command shows the following (indentations are gone):
If we use …
> Update `ads opctl run -b local` to print container logs and log docker run cmd for debugging.

- CONTRIBUTING.md
Added information about which branching strategy we follow in ADS projects, for new contributors. This change needed after we changed GitFlow dev process to GitHub flow, described here: https://www.alexhyett.com/git-flow-github-flow/#what-is-github-flow
> Update CONTRIBUTING.md with GitHub flow branching strategy.

- docs/source/user_guide/jobs/infra_and_runtime.rst
- docs/source/user_guide/jobs/tabs/infra_config.rst
- docs/source/user_guide/jobs/tabs/quick_start_job.rst
> Updated mounting file systems in job docs.

- docs/source/user_guide/jobs/infra_and_runtime.rst
- docs/source/user_guide/jobs/tabs/infra_config.rst
- docs/source/user_guide/jobs/tabs/quick_start_job.rst
Reverts oracle/accelerated-data-science#192
> Revert "Updated mounting file systems in job docs." (waiting service GA)

- ads/feature_store/common/utils/utility.py
- ads/feature_store/data_validation/great_expectation.py
- ads/feature_store/execution_strategy/spark/spark_execution.py
code changes to tie ingestion and validation
> code changes to tie ingestion and validation

- .gitleaks.toml
- .pre-commit-config.yaml
- ads/common/oci_client.py
- ads/common/oci_mixin.py
- ads/common/serializer.py
- ads/jobs/__init__.py
- ads/jobs/ads_job.py
- ads/jobs/builders/infrastructure/dsc_job.py
- ads/jobs/builders/infrastructure/dsc_job_runtime.py
- ads/jobs/builders/runtimes/artifact.py
- ads/jobs/builders/runtimes/python_runtime.py
- ads/jobs/builders/runtimes/pytorch_runtime.py
- ads/jobs/serializer.py
- ads/jobs/templates/driver_oci.py
- ads/jobs/templates/driver_pytorch.py
- ads/jobs/templates/driver_utils.py
- ads/jobs/templates/hostname_from_env.c
- ads/jobs/templates/oci_metrics.py
- ads/model/framework/pytorch_model.py
- ads/opctl/docker/Dockerfile.job
- ads/opctl/docker/Dockerfile.job.gpu
- ads/opctl/docker/base-env.yaml
- setup.py
- tests/unitary/default_setup/jobs/test_gpu_metrics.py
- tests/unitary/default_setup/jobs/test_jobs_pytorch_ddp.py
- tests/unitary/with_extras/jobs/__init__.py
- tests/unitary/with_extras/jobs/test_pytorch_ddp.py
- tests/unitary/with_extras/opctl/test_opctl_local_backend.py
- tests/unitary/with_extras/opctl/test_opctl_local_model_deployment_backend.py
Fix ADS unittests on feature store branch
> Odsc 44980: fix unittests

- ads/dataset/dataset.py
- ads/dataset/dataset_browser.py
- ads/dataset/factory.py
- ads/dataset/helper.py
- Deprecated `DatasetFactory` in ads `2.8.8`
- Moved and refactored internally-used APIs from `DatasetFactory` to `helper` class
> Deprecated DatasetFactory class and refactored code.

- ads/opctl/operator/cmd.py
- ads/opctl/operator/lowcode/forecast/__init__.py
- ads/opctl/operator/lowcode/forecast/model/automlx.py
- ads/opctl/operator/lowcode/forecast/utils.py
* Installing libX11 library inside the container as it is required for automlx. 
* automlx model fix
* fixed function `human_time_friendly`, It was failing when `seconds < 1`
> fixes in forecast operator

- ads/feature_store/common/spark_session_singleton.py
- ads/feature_store/common/utils/transformation_utils.py
- ads/feature_store/dataset.py
- ads/feature_store/docs/source/dataset.rst
- ads/feature_store/docs/source/feature_group.rst
- ads/feature_store/execution_strategy/engine/spark_engine.py
- ads/feature_store/feature_group.py
- tests/integration/feature_store/test_as_of_for_featuregroup_and_dataset.py
- tests/integration/feature_store/test_base.py
added as_of interface to the feature store
> added as_of interface to the feature store

- ads/opctl/operator/lowcode/forecast/model/base_model.py
- ads/opctl/operator/lowcode/forecast/operator_config.py
- ads/opctl/operator/lowcode/forecast/schema.yaml
Made `confidence_interval_width`, `test_data` and `output_directory` optional parameters
> optional params fixes

- ads/opctl/operator/lowcode/forecast/model/factory.py
- ads/opctl/operator/lowcode/forecast/schema.yaml
- ads/opctl/operator/lowcode/forecast/utils.py
Added auto option in schema.yaml and added a function in utils.py to select arima if number of cols > 15, otherwise automlx
> Added auto option in schema.yaml

- ads/opctl/operator/lowcode/forecast/model/base_model.py
- ads/opctl/operator/lowcode/forecast/model/transformations.py
- ads/opctl/operator/lowcode/forecast/schema.yaml
* Added basic transformation for missing value imputation and outlier treatment.
* Tested on EPM dataset for both Prophet and ARIMA, SMAPE and MAPE is improving after the change. 
For ARIMA
Mean SMAPE improved from 23.92 to 19.69
Mean MAPE improved from 2.57 to 1.22
Mean RMSE improved from 1534 to 1462
For Prophet 
Mean SMAPE improved from 29.32 to 29.30
Mean MAPE improved from 10.14 to 9.57
Mean RMSE deteriorate from 1657 to 1771
* Other minor fixes (removed test_data as required parameter)
> added basic transformations

- ads/feature_store/dataset.py
- ads/feature_store/docs/source/dataset.rst
- ads/feature_store/feature_group.py
- ads/feature_store/mixin/oci_feature_store.py
- tests/integration/feature_store/test_feature_group_dataset_listing.py
- tests/unitary/with_extras/feature_store/test_dataset.py
- tests/unitary/with_extras/feature_store/test_feature_group.py
add dataset.get_features_df  and dataset.get_features interfaces
update documentation and minor bug fix
> Odsc 45131/ads interfaces

- ads/common/auth.py
- ads/opctl/cli.py
- Expanding the security file path when trying to fetch it
> Expand security file path

- ads/opctl/operator/lowcode/forecast/const.py
- ads/opctl/operator/lowcode/forecast/utils.py
Added description for select_auto_model method. Moved 15 i.e; number that is used to select between AutoMLX, Arima for auto option to consts.py
> ODSC-46046/add_auto_option 

- ads/opctl/operator/lowcode/forecast/README.md
- ads/opctl/operator/lowcode/forecast/environment.yaml
- ads/opctl/operator/lowcode/forecast/model/automlx.py
https://jira.oci.oraclecorp.com/browse/ODSC-46956
- Upgraded automlx version from v23.2.1 to v23.2.2.
- Tested the changes with conda environment.
> Automlx upgrade from 23.2.1 to 23.2.2

- ads/model/model_artifact_boilerplate/artifact_introspection_test/model_artifact_validate.py
- Fixed the model artifact validation issue when calling `generic_model.save()`.
- warning message
> Fixed generic model save() issue

- pyproject.toml
Bump version to 2.9.0rc0
Run 'make dist' command, proper version builded
> ADS pre-release v2.9.0rc0

- docs/source/user_guide/model_registration/introduction.rst
- docs/source/user_guide/model_registration/large_language_model.rst
- docs/source/user_guide/model_registration/model_load.rst
- docs/source/user_guide/model_registration/tabs/ads-md-deploy-offline.rst
- docs/source/user_guide/model_registration/tabs/ads-md-deploy-online.rst
- docs/source/user_guide/model_registration/tabs/ads-md-deploy.rst
- docs/source/user_guide/model_registration/tabs/env-var-offline.rst
- docs/source/user_guide/model_registration/tabs/env-var-online.rst
- docs/source/user_guide/model_registration/tabs/run_md.rst
- docs/source/user_guide/model_registration/tabs/run_predict.rst
JIRA: https://jira.oci.oraclecorp.com/browse/ODSC-47401
Creates a section in the Registration Model, showing how to act with the LLM models. 
```
git checkout ODSC-47401/llm_model_registration
cd docs
make zip
```
The built doc can be found on `build/html/user_guide/model_registration/large_language_model.html`
https://github.com/oracle-samples/oci-data-science-ai-samples/tree/main/model-deployment/containers/llama2
https://blogs.oracle.com/ai-and-datascience/post/llama2-oci-data-science-cloud-platform
> [DOCS] Large Language Model section.

- docs/source/user_guide/jobs/infra_and_runtime.rst
- docs/source/user_guide/jobs/tabs/infra_config.rst
- docs/source/user_guide/jobs/tabs/quick_start_job.rst
> Added docs for mounting file systems for job.

- ads/opctl/backend/ads_ml_job.py
- ads/opctl/backend/local.py
- tests/unitary/with_extras/operator/test_files/test_operator/MLoperator
- tests/unitary/with_extras/operator/test_operator_backend.py
https://jira.oci.oraclecorp.com/browse/ODSC-47050
https://jira.oci.oraclecorp.com/browse/ODSC-46763
* Adds unit tests for the operator local backend
* Adds unit tests for the operator jobs backend
> ODSC-47050: Adds unit tests for the operator backends.

- ads/opctl/operator/lowcode/forecast/utils.py
[ODSC-49029](https://jira.oci.oraclecorp.com/browse/ODSC-49029)
> Bug Fix : Dropping target column if present in additional data

- ads/opctl/operator/lowcode/forecast/model/arima.py
- ads/opctl/operator/lowcode/forecast/model/automlx.py
- ads/opctl/operator/lowcode/forecast/model/autots.py
- ads/opctl/operator/lowcode/forecast/model/base_model.py
- ads/opctl/operator/lowcode/forecast/model/prophet.py
- ads/opctl/operator/lowcode/forecast/operator_config.py
- ads/opctl/operator/lowcode/forecast/schema.yaml
- add local & global explanation for ARIMA model
- add reports with normalized explainability score.
ARIMA model explanation on a sample dataset:
- Global Exp:
- Local Exp:
> [ODSC-48857 | ODSC-48858] Global Explainability & Local Explainability - ARIMA

- ads/common/utils.py
- ads/model/runtime/utils.py
Fixes the service conda environments PAR link.
> ODSC-49489: Fix service conda environments PAR link.

- .github/workflows/run-unittests-py38-cov-report.yml
- .github/workflows/run-unittests-py39-py310.yml
- dev-requirements.txt
- docs/source/release_notes.rst
- pyproject.toml
Running release v2.9.0. Jira: https://jira.oci.oraclecorp.com/browse/ODSC-48017
- bumped version to 2.9.0
```
check python ast.....................................(no files to check)Skipped
check docstring is first.............................(no files to check)Skipped
detect private key.......................................................Passed
fix end of files.........................................................Passed
pretty format json...................................(no files to check)Skipped
trim trailing …
```
> ADS release 2.9.0

- ads/opctl/operator/lowcode/anomaly/cmd.py
https://jira.oci.oraclecorp.com/browse/ODSC-50138
Fixes AD operator init yaml formatting.
> Fixes init yaml formatting for AD operator

- ads/llm/langchain/plugins/llm_md.py
> Set endpoint through env var

- docs/source/user_guide/large_language_model/deploy_langchain_application.rst
> Updated langchain user guide.

- ads/feature_store/common/utils/transformation_utils.py
- ads/feature_store/docs/source/feature_store.rst
- ads/feature_store/docs/source/transformation.rst
- ads/feature_store/feature_store.py
- ads/feature_store/transformation.py
> Feature store display name to name changes

- ads/feature_store/execution_strategy/spark/spark_execution.py
> fixed restore

- ads/common/dsc_file_system.py
- tests/unitary/default_setup/jobs/test_jobs_mount_file_system.py
> Removed `dest` Precheck

- ads/opctl/operator/lowcode/forecast/const.py
- ads/opctl/operator/lowcode/forecast/model/arima.py
- ads/opctl/operator/lowcode/forecast/model/automlx.py
- ads/opctl/operator/lowcode/forecast/model/autots.py
- ads/opctl/operator/lowcode/forecast/model/base_model.py
- ads/opctl/operator/lowcode/forecast/model/forecast_datasets.py
- ads/opctl/operator/lowcode/forecast/model/prophet.py
- ads/opctl/operator/lowcode/forecast/operator_config.py
- ads/opctl/operator/lowcode/forecast/schema.yaml
[ODSC-50379](https://jira.oci.oraclecorp.com/browse/ODSC-50379)
* Introduced three modes of explainability HIGH_ACCURACY, BALANCED and FAST_APPROXIMATE.
* Moved away from KernelExplainer to PermutationExplainer to generate explanations faster.
> Forecast V2 Fast Explainability

- ads/jobs/builders/runtimes/container_runtime.py
- docs/source/user_guide/jobs/data_science_job.rst
> Updated job docs

- ads/opctl/operator/lowcode/forecast/model/autots.py
Historical fitted values for the AutoTS model
> Historical fitted values for the AutoTS model

- ads/llm/langchain/plugins/base.py
- ads/llm/langchain/plugins/contant.py
- ads/llm/langchain/plugins/embeddings.py
- ads/llm/langchain/plugins/llm_gen_ai.py
- docs/source/user_guide/large_language_model/index.rst
- docs/source/user_guide/large_language_model/langchain_models.rst
- docs/source/user_guide/large_language_model/retrieval.rst
The OCI Generative AI is introducing breaking change. This update will support the new APIs.
> Update Generative AI LLM model to use new APIs.

- docs/source/release_notes.rst
- pyproject.toml
Running release v2.10.0. Jira: https://jira.oci.oraclecorp.com/browse/ODSC-50746
- bumped version to 2.10.0
> ADS release v2.10.0

- ads/aqua/cli.py
- ads/aqua/extension/__init__.py
- ads/aqua/extension/base_handler.py
- ads/aqua/extension/job_handler.py
- ads/aqua/extension/model_handler.py
- ads/aqua/extension/playground_handler.py
- ads/aqua/playground/__init__.py
- ads/aqua/playground/const.py
- ads/aqua/playground/db_context.py
- ads/aqua/playground/db_models.py
- ads/aqua/playground/entities.py
- ads/aqua/playground/errors.py
- ads/aqua/playground/playground.py
- ads/cli.py
- ads/common/decorator/__init__.py
- ads/common/decorator/require_nonempty_arg.py
- ads/common/serializer.py
- pyproject.toml
- tests/unitary/default_setup/common/test_require_nonempty_arg.py
- tests/unitary/with_extras/aqua/test_playground.py
- tests/unitary/with_extras/aqua/test_playground_entities.py
- tests/unitary/with_extras/aqua/test_playground_handler.py
https://jira.oci.oraclecorp.com/browse/ODSC-51833
Implements Backend Component for the Playground
In the current implementation the invoking model utilizes the ```ModelDeploymentVLLM``` class which has dependency on the LangChain package. This will be improved in the upcoming PR.
* sqlalchemy>=2.0.25
* langchain 
To test handlers oyu will need to run ADS and JupyterLab.
Add the extension to Jupyter Lab: ```jupyter serverextension enable --py ads.aqua.extension```
Start Jupyter Lab ```jupyter lab``` or ```jupyter lab --no-browser```.
```
ads aqua playground session create --model_id ocid1.datasciencemodeldeployment.oc1.iad....
```
```
ads aqua playground session list
```
By model ID (Model Deployment)
```
ads aqua playground session get --id ocid1.datasciencemodeldeployment.oc1.iad..... …
```
> Playground API

- ads/aqua/base.py
- ads/aqua/deployment.py
Adding additional fields for UI.
> Deployment params for UI

- ads/common/auth.py
- ads/opctl/config/merger.py
- ads/opctl/utils.py
[ODSC-51737](https://jira.oci.oraclecorp.com/browse/ODSC-51737)
Added static function supported in ResourcePrincipal, to default to RP
> Operator in Jobs should auto-detect RP

- ads/aqua/deployment.py
- ads/aqua/model.py
This PR is for revisiting the error handler once it's finalized and addressing some comments.
> Revisit error handler

- ads/aqua/deployment.py
- ads/aqua/extension/deployment_handler.py
- ads/aqua/model.py
1. Create a new model and copy service model artifacts under user's compartment and project.
2. Revisit the error handler
> Create Aqua Model

- ads/opctl/operator/lowcode/anomaly/model/base_model.py
- ads/opctl/operator/lowcode/common/utils.py
- ads/opctl/operator/lowcode/forecast/model/base_model.py
[ODSC-51508] Extended for AD
- refactor to results dir unique path to common utils
- update for the anomaly detection default directory
> [ODSC-51508]  : Refactor results dir unique path creation

- ads/opctl/operator/lowcode/anomaly/model/base_model.py
[ODSC-51511](https://jira.oci.oraclecorp.com/browse/ODSC-51511)
add fallback using one-class SVM with SGD, 
- this fallback will be used upon failure of the sub-model _build_model methods
> ODSC-51511 : Fallback method to train model for the AD models

- docs/source/release_notes.rst
- pyproject.toml
Running release v2.10.1. Jira: https://jira.oci.oraclecorp.com/browse/ODSC-52257
- bumped version to 2.10.1
> ADS release v2.10.1

- ads/aqua/model.py
load_icon moved to AquaModelSummary
> load_icon moved to AquaModelSummary

- ads/jobs/builders/infrastructure/dsc_job.py
- ads/jobs/builders/runtimes/base.py
- ads/jobs/builders/runtimes/container_runtime.py
- ads/jobs/builders/runtimes/pytorch_runtime.py
Reusing the logic from PyTorchDistributedRuntime in ContainerRuntime.
> Support Distributed Training with Container Jobs.

- ads/aqua/evaluation.py
- ads/aqua/extension/__init__.py
- ads/aqua/extension/evaluation_handler.py
- ads/aqua/extension/ui_handler.py
- ads/aqua/ui.py
This PR aims to setup handler for evaluation. It also provides sample response for apis. Actual implementation will be in another PR after this.
Please checkout confluence page for more details.
```
POST http://localhost:8888/aqua/evaluation/
GET http://localhost:8888/aqua/evaluation/
GET http://localhost:8888/aqua/evaluation/ocid1.datasciencemodel.<OCID>
GET http://localhost:8888/aqua/evaluation/ocid1.datasciencemodel.<OCID>/metrics
GET http://localhost:8888/aqua/evaluation/ocid1.datasciencemodel.<OCID>/report
GET http://localhost:8888/aqua/experiment/
DELETE http://localhost:8888/aqua/evaluation/ocid1.datasciencemodel.oc1.iad.<OCID>
PUT http://localhost:8888/aqua/evaluation/ocid1.datasciencemodel.oc1.iad.<OCID>/cancel
```
> build base class and construct sample response

- ads/aqua/evaluation.py
- ads/aqua/utils.py
Merging Lu's code into feature/aqua
> Patching for create

- ads/aqua/evaluation.py
- ads/aqua/utils.py
Return service status instead of our own status.
> aqua/fix/evaluation status 

- ads/aqua/evaluation.py
- tests/unitary/with_extras/aqua/test_evaluation.py
> ODSC-53932/get correct status when missing jobrun

- ads/aqua/data.py
- ads/aqua/evaluation.py
- ads/aqua/extension/evaluation_handler.py
- ads/aqua/utils.py
- tests/unitary/with_extras/aqua/test_evaluation.py
Updated the confluence page with new response.
> AQUA/EVAL/improvement on create/list/get

- ads/aqua/evaluation.py
- ads/aqua/utils.py
> improve apis by requirements

- ads/aqua/evaluation.py
Updates the evaluation container version to the 0.0.2.10
> Updates the evaluation container version to 0.0.2.10

- ads/aqua/evaluation.py
- ads/aqua/utils.py
Cleanup evaluation API constants.
> Cleanup evaluation API constants.

- ads/aqua/evaluation.py
This Pull Request enhances the metadata for evaluation:
* Adds ```dataset_path```
* Adds ```report_path```
> Extends the evaluation metadata hyperparameters.

- ads/aqua/extension/__init__.py
- ads/aqua/extension/common_handler.py
Introduces a common AQUA handler to fetch the ADS version.
```/aqua/ads_version```
> Adds AQUA common handler to fetch the ADS version.

- ads/aqua/evaluation.py
Introduces a ROUGE score metric to the AQUA evaluation.
> Introduces a ROUGE score metric to the AQUA evaluation.

- ads/opctl/operator/lowcode/anomaly/README.md
- ads/opctl/operator/lowcode/anomaly/environment.yaml
- ads/opctl/operator/lowcode/anomaly/model/automlx.py
- ads/opctl/operator/lowcode/forecast/README.md
- ads/opctl/operator/lowcode/forecast/environment.yaml
- ads/opctl/operator/lowcode/forecast/model/automlx.py
- docs/source/user_guide/operators/anomaly_detection_operator/faq.rst
- docs/source/user_guide/operators/forecasting_operator/faq.rst
- pyproject.toml
- tests/operators/anomaly/test_anomaly_simple.py
- tests/operators/forecast/test_datasets.py
- tests/operators/forecast/test_errors.py
- tests/unitary/with_extras/langchain/test_serialization.py
- Upgraded AutoMLx from `23.2.3` to `23.4.1`
- Switched AutoMLx engine to use Ray.
> AutoMLx Upgrade 

- ads/aqua/evaluation.py
- ads/aqua/finetune.py
Passes the conda bucket namespace environment variable for telemetry within evaluation and fine-tuning jobs.
> Passes telemetry namespace to the evaluation and fine-tuning jobs.

- docs/source/release_notes.rst
- pyproject.toml
Running release v2.11.0. Jira: https://jira.oci.oraclecorp.com/browse/ODSC-52758
- bumped version to 2.11.0
> ADS release v2.11.0

- docs/source/release_notes.rst
- pyproject.toml
Running release v2.11.1
- Fixes the project file
- Bumps the version to 2.11.1
> ADS release v2.11.1

- THIRD_PARTY_LICENSES.txt
- ads/aqua/base.py
- ads/aqua/data.py
- ads/aqua/deployment.py
- ads/aqua/evaluation.py
- ads/aqua/finetune.py
- ads/aqua/model.py
- ads/aqua/training/exceptions.py
- ads/aqua/ui.py
- ads/aqua/utils.py
- ads/config.py
- ads/model/datascience_model.py
- docs/source/release_notes.rst
- pyproject.toml
- tests/unitary/default_setup/model/test_datascience_model.py
- tests/unitary/with_extras/aqua/test_evaluation.py
- tests/unitary/with_extras/aqua/test_model.py
- tests/unitary/with_extras/aqua/test_utils.py
Running release v2.11.2.
- bumped version
- squashed commits from feature/aqua branch
> ADS release v2.11.2

- ads/aqua/evaluation.py
Removes Arm shape from the list supported by the evaluation.
> Removes Arm shape from the list supported by the evaluation.

- docs/source/release_notes.rst
- pyproject.toml
Running release v2.11.3.
- Removes Arm shape from the list supported by the evaluation.
> ADS release v2.11.3

- docs/source/release_notes.rst
- pyproject.toml
Running release v2.11.4
* Compatibility check for Aqua extension and update compartment mapping config
> ADS Release v2.11.4

- ads/model/model_artifact_boilerplate/artifact_introspection_test/model_artifact_validate.py
- docs/source/user_guide/model_serialization/automlmodel.rst
- tests/unitary/default_setup/model/test_model_introspect.py
Fix for https://github.com/oracle/accelerated-data-science/issues/760
> Python Validation error and doc fix

- .github/workflows/run-operators-unit-tests.yml
- ads/common/serializer.py
- ads/opctl/operator/lowcode/forecast/environment.yaml
- pyproject.toml
- test-requirements-operators.txt
> ODSC-55407

- docs/source/index.rst
> Add AI quick actions link

- tests/operators/forecast/test_errors.py
Updated unit tests according to the latest schema changes merged into main.
> Updated forecast operator unit tests 

- ads/aqua/evaluation.py
- ads/config.py
Adds supporting BLEU score metric for evaluation.
> Adds supporting BLEU score metric for evaluation.

- ads/aqua/deployment.py
This PR takes care of the following:
1. Simplify and remove redundant code in create method.
2. Add "ocid=last_8_digits_of_MD_ID" as telemetry value when creating MD. This gets us logs like:
```
{"datetime": 1712689489086, "category": "aqua/service/deployment/create", "action": "model-name", "value": "ocid=3kmulq12", ...
```
or 
```
{"datetime": 1712689489086, "category": "aqua/custom/deployment/create", "action": "ft-base-model-name", "value": "ocid=3kmulq12", ...
```
3. Add ocid and lifecycle state when listing deployments. This logs telemetry information only if state is active or failed to avoid unnecessary logging of other states that won't be much useful to us.This gives us logs like:
```
{"datetime": 1712689489086, "category": "aqua/deployment/list", "action": "3kmulq12", "value": …
```
> [ODSC-56061] Update Model deployment telemetry

- ads/aqua/__init__.py
- ads/aqua/evaluation.py
- ads/aqua/utils.py
This PR aims to followup the comment in #795 to reuse the logger in ads.init.
> Followup comment in #795: reuse the logger in ads.init

- tests/unitary/with_extras/aqua/test_global.py
`configure_aqua_logger` has been removed from code base.
> Removed redundant test

- ads/model/deployment/model_deployment.py
Adds id property to ModelDeployment class.
> Adds id property to ModelDeployment class.

- ads/aqua/extension/model_handler.py
- ads/aqua/extension/ui_handler.py
- ads/aqua/model.py
- ads/aqua/ui.py
- tests/unitary/with_extras/aqua/test_data/ui/container_index.json
- tests/unitary/with_extras/aqua/test_model_handler.py
- tests/unitary/with_extras/aqua/test_ui.py
- tests/unitary/with_extras/aqua/test_ui_handler.py
https://jira.oci.oraclecorp.com/browse/ODSC-56764
* Adds a handler to list service containers
```
http://localhost:8888/aqua/containers
```
**SRC**
```
{
"odsc-llm-evaluate": [
{
"name": "dsmc://odsc-llm-evaluate",
"version": "0.1.2.0"
}
],
"odsc-llm-fine-tuning": [
{
"name": "dsmc://odsc-llm-fine-tuning",
"version": "1.1.33.34"
}
],
"odsc-tgi-serving": [
{
"displayName": "TGI:1.4.5",
"name": "dsmc://odsc-tgi-serving",
"type": "inference",
"version": "1.4.5"
},
{
"displayName": "TGI:2.0.2",
"name": "dsmc://odsc-tgi-serving",
"type": "inference",
"version": "2.0.2"
}
],
"odsc-vllm-serving": [
{
"displayName": "VLLM:0.3.0",
"name": "dsmc://odsc-vllm-serving",
"type": "inference",
"version": "0.3.0.7"
}
]
}
```
**RESULT**
```
{
"inference": [
{
"name": "dsmc://odsc-tgi-serving",
"version": …
```
> Adds a handler to list service containers.

- ads/aqua/extension/model_handler.py
- ads/aqua/model.py
- ads/aqua/utils.py
- tests/unitary/with_extras/aqua/test_model.py
- tests/unitary/with_extras/aqua/test_model_handler.py
https://jira.oci.oraclecorp.com/browse/ODSC-56571
Adds additional fields into the  ```AquaModel``` class.  
- inference_container: str = None
- finetuning_container: str = None
- evaluation_container: str = None
**The fields will be populated in the requests:**
- aqua/model/hf/search
- aqua/model/get
> AQUA. Adds additional fields into the AquaModel class.

- ads/opctl/operator/lowcode/anomaly/model/base_model.py
Fixed the references to the target column.
> BUG: Fallback model referencing target series rather than the target column

- ads/aqua/extension/model_handler.py
- ads/aqua/model.py
- tests/unitary/with_extras/aqua/test_model.py
* deleted method `_fetch_defaults_for_hf_model`
* Added logic to fetch model ocid if register command receives HF model name instead of ocid
> check if HF model input during register is available as shadow model

- ads/aqua/app.py
- ads/aqua/common/utils.py
- ads/aqua/constants.py
- ads/aqua/evaluation/evaluation.py
- ads/aqua/finetuning/finetuning.py
- ads/aqua/model/model.py
- ads/aqua/modeldeployment/deployment.py
- ads/aqua/modeldeployment/entities.py
- tests/unitary/with_extras/aqua/test_common_handler.py
- tests/unitary/with_extras/aqua/test_evaluation.py
> Aqua refactor: use const in aqua.constants.py 

- ads/aqua/common/enums.py
- ads/aqua/evaluation/constants.py
- ads/aqua/evaluation/evaluation.py
merged and reused Tags, addressed TODO, removed duplicated class, some improvements on functions.
> Aqua refactor: improvement on evaluation.py

- docs/source/release_notes.rst
- pyproject.toml
Bumped version and added release notes for ADS release v2.11.14.
> ADS release v2.11.14

- ads/opctl/operator/lowcode/forecast/model/arima.py
[ODSC-60331](https://jira.oci.oraclecorp.com/browse/ODSC-60331)
> Fixed target removal if all unique values

- ads/aqua/evaluation/evaluation.py
- ads/aqua/modeldeployment/deployment.py
The logic present here was meant to handle ocir values which didn't have dsmc:// at the front. Have corrected the logic to handle both dsmc and ocir
> Update evaluation params logic

- ads/opctl/operator/lowcode/forecast/model/arima.py
- ads/opctl/operator/lowcode/forecast/model/automlx.py
- ads/opctl/operator/lowcode/forecast/model/autots.py
- ads/opctl/operator/lowcode/forecast/model/ml_forecast.py
- ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
- ads/opctl/operator/lowcode/forecast/model/prophet.py
[ODSC-61446](https://jira.oci.oraclecorp.com/browse/ODSC-61446)
> Automlx | Logging errors in `error.csv` when all forecast values are NaN.

- ads/aqua/modeldeployment/deployment.py
- Registered with vllm container:
- Overrided with TGI container:
> Fix override container family

- .github/workflows/run-unittests-py38-cov-report.yml
- docs/source/release_notes.rst
- pyproject.toml
Updated version and added release notes.
> Release notes for v2.11.19

- docs/source/release_notes.rst
- docs/source/user_guide/large_language_model/langchain_models.rst
Update LangChain Integration to add support for chat model, streaming and async calls.
> Release note for v2.11.20.

- ads/aqua/evaluation/evaluation.py
> Fixed error while list evaluations

- docs/source/release_notes.rst
- pyproject.toml
Bumps the ADS version to 2.12.5
* Fixed bugs in the AI Quick Actions Evaluation.
> Bumps the ADS version to 2.12.5

- docs/source/release_notes.rst
- pyproject.toml
* Fixed bugs in the AI Quick Actions Evaluation.
> Bumps the ADS version to 2.12.7

- docs/source/user_guide/large_language_model/langchain_models.rst
- docs/source/user_guide/model_registration/large_language_model.rst
- Updated langchain doc to use generic classes and added example for `default_headers`
- Added note to use AQUA in `Large Language Model`
> Updated ADS docs

- ads/aqua/modeldeployment/entities.py
- ads/aqua/modeldeployment/utils.py
- tests/unitary/with_extras/aqua/test_deployment.py
Enhances the multi-model configuration retrieval process.
> Enhances the multi-model configuration retrieval process.

- ads/opctl/operator/lowcode/forecast/model/arima.py
- ads/opctl/operator/lowcode/forecast/model/automlx.py
- ads/opctl/operator/lowcode/forecast/model/base_model.py
- ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
- ads/opctl/operator/lowcode/forecast/model/prophet.py
- ads/opctl/operator/lowcode/forecast/whatifserve/score.py
- tests/operators/forecast/test_errors.py
[ODSC-65638](https://jira.oci.oraclecorp.com/browse/ODSC-65638)
This PR improves the What-If Analysis feature by supporting non-numeric columns. Some models apply label encoding and remove constant columns before fitting. To maintain consistency, these transformations are saved and reapplied during real time prediction.
> Support for Non-Numeric Columns in What-If Analysis

- ads/aqua/extension/base_handler.py
- ads/aqua/server/__init__.py
- ads/aqua/server/__main__.py
- ads/aqua/server/app.py
- ads/aqua/server/aqua_spec.yml
- docs/source/index.rst
- docs/source/user_guide/aqua/apiserver.rst
- pyproject.toml
Ability to launch AI Quick Actions API server from anywhere. Just run - 
`python -m ads.aqua.server`
> support to launch Aqua services without jupyterlab (#1075)

- ads/aqua/modeldeployment/utils.py
- tests/unitary/with_extras/aqua/test_deployment.py
> Collect shape from configuration entry.

- docs/source/release_notes.rst
- pyproject.toml
* Fixed bug in DataScienceModel defined metadata.
> Bumps the ADS version to 2.13.2

- docs/source/release_notes.rst
- pyproject.toml
> Bumps ADS version to 2.13.4

- docs/source/user_guide/large_language_model/autogen_integration.rst
* Fix error in the example code.
* Add link to example notebook.
> Update AutoGen docs

- ads/aqua/model/model.py
Adds support for `image-text-to-text` models in multi-model deployment.
> Relaxes the validation of model task types during multi-model deployment creation.

- docs/source/release_notes.rst
- pyproject.toml
* AI Quick Actions: Adds support for ``image-text-to-text`` models in multi-model deployment.
> Bumps ADS version to 2.13.8

- ads/aqua/config/container_config.py
- tests/unitary/with_extras/aqua/test_ui.py
Enhances the AQUA model deployment logic by mapping the VLLM architecture version defined in the global container configuration to the appropriate environment variable expected by the VLLM container.
> Enhance AQUA SDK to Inject VLLM_USE_V1 Based on Global Container Config

- docs/source/user_guide/large_language_model/aqua_client.rst
- docs/source/user_guide/large_language_model/llamaindex_integration.rst
Update AQUA client documentation to Support `/predictWithResponseStream` Endpoint
> [AQUA] Update AQUA client documentation to Support predictWithResponseStream Endpoint

- tests/unitary/with_extras/aqua/test_deployment.py
- Tested building `ModelGroupConfig` class for two use cases:
-- with fine tuned model
-- without fine tuned model
These models will have gpu assigned as 1, 2, 4, respectively, which covers all cases when the **key** of `parameters` is:
- available in `multi_model_deployment` and has a value.
- available in `multi_model_deployment` and has an empty value.
- unavailable in `multi_model_deployment` so value of `parameters` on root level is used.
```
============================================= test session starts =============================================
platform darwin -- Python 3.13.2, pytest-8.3.5, pluggy-1.5.0 -- /Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13
configfile: …
```
> Added unit test for ModelGroupConfig class.

- docs/source/release_notes.rst
- pyproject.toml
* Enhance the AQUA OpenAI-compatible client to support multiple inference endpoints within OCI Model Deployment.
* Add support for time series forecasting models in AQUA.
* Improve the AQUA CLI by adding a policy verification check for operations related to AQUA.
* Introduce support for chat templates in AQUA.
> Releases the ADS v2.13.13

- ads/aqua/app.py
- ads/aqua/common/enums.py
- ads/aqua/finetuning/constants.py
- ads/aqua/finetuning/finetuning.py
- Added tag `fine_tune_model_version=v2` in ft model for finetune container to block merging base model artifacts with ft model artifacts.
> Added support for ft model v2.

- docs/source/release_notes.rst
- pyproject.toml
* AI Quick Actions enhancements.
> Releases the ADS v2.13.17

- ads/opctl/operator/lowcode/forecast/__init__.py
[ODSC-75703](https://jira.oci.oraclecorp.com/browse/ODSC-75703)
Changes to make Prophet confidence intervals consistent across runs.
> Fix Prophet CI inconsistency

- docs/source/release_notes.rst
- pyproject.toml
* AI Quick Actions enhancements.
* MLPipeline: Fixed a bug preventing users from creating a pipeline step with a specific subnet_id.
> Releases ADS v2.13.18

- ads/aqua/evaluation/evaluation.py
- Fixed evaluation validation for model group deployment.
> Fixed evaluation validation for model group deployment.

- ads/aqua/modeldeployment/deployment.py
- tests/unitary/with_extras/aqua/test_deployment.py
> Add blocker for multi deployment
